# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument,unused-import

import math
import typing as T

import numpy

import sym


def ctrl(ierr, p, v, logR, w, p_d, v_d, a_d, w_d, theta_pos, theta_rot, dt):
    # type: (numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, float) -> T.Tuple[numpy.ndarray, numpy.ndarray]
    """
    This function was autogenerated from a symbolic function. Do not modify by hand.

    Symbolic function: ctrl_symfn

    Args:
        ierr: Matrix31
        p: Matrix31
        v: Matrix31
        logR: Matrix31
        w: Matrix31
        p_d: Matrix31
        v_d: Matrix31
        a_d: Matrix31
        w_d: Matrix31
        theta_pos: Matrix61
        theta_rot: Matrix41
        dt: Scalar

    Outputs:
        thrust_torque: Matrix41
        jacobian: (4x25) jacobian of thrust_torque wrt args ierr (3), p (3), v (3), logR (3), w (3),
                  theta_pos (6), theta_rot (4)
    """

    # Total ops: 1516

    # Input arrays
    if ierr.shape == (3,):
        ierr = ierr.reshape((3, 1))
    elif ierr.shape != (3, 1):
        raise IndexError(
            "ierr is expected to have shape (3, 1) or (3,); instead had shape {}".format(ierr.shape)
        )

    if p.shape == (3,):
        p = p.reshape((3, 1))
    elif p.shape != (3, 1):
        raise IndexError(
            "p is expected to have shape (3, 1) or (3,); instead had shape {}".format(p.shape)
        )

    if v.shape == (3,):
        v = v.reshape((3, 1))
    elif v.shape != (3, 1):
        raise IndexError(
            "v is expected to have shape (3, 1) or (3,); instead had shape {}".format(v.shape)
        )

    if logR.shape == (3,):
        logR = logR.reshape((3, 1))
    elif logR.shape != (3, 1):
        raise IndexError(
            "logR is expected to have shape (3, 1) or (3,); instead had shape {}".format(logR.shape)
        )

    if w.shape == (3,):
        w = w.reshape((3, 1))
    elif w.shape != (3, 1):
        raise IndexError(
            "w is expected to have shape (3, 1) or (3,); instead had shape {}".format(w.shape)
        )

    if p_d.shape == (3,):
        p_d = p_d.reshape((3, 1))
    elif p_d.shape != (3, 1):
        raise IndexError(
            "p_d is expected to have shape (3, 1) or (3,); instead had shape {}".format(p_d.shape)
        )

    if v_d.shape == (3,):
        v_d = v_d.reshape((3, 1))
    elif v_d.shape != (3, 1):
        raise IndexError(
            "v_d is expected to have shape (3, 1) or (3,); instead had shape {}".format(v_d.shape)
        )

    if a_d.shape == (3,):
        a_d = a_d.reshape((3, 1))
    elif a_d.shape != (3, 1):
        raise IndexError(
            "a_d is expected to have shape (3, 1) or (3,); instead had shape {}".format(a_d.shape)
        )

    if w_d.shape == (3,):
        w_d = w_d.reshape((3, 1))
    elif w_d.shape != (3, 1):
        raise IndexError(
            "w_d is expected to have shape (3, 1) or (3,); instead had shape {}".format(w_d.shape)
        )

    if theta_pos.shape == (6,):
        theta_pos = theta_pos.reshape((6, 1))
    elif theta_pos.shape != (6, 1):
        raise IndexError(
            "theta_pos is expected to have shape (6, 1) or (6,); instead had shape {}".format(
                theta_pos.shape
            )
        )

    if theta_rot.shape == (4,):
        theta_rot = theta_rot.reshape((4, 1))
    elif theta_rot.shape != (4, 1):
        raise IndexError(
            "theta_rot is expected to have shape (4, 1) or (4,); instead had shape {}".format(
                theta_rot.shape
            )
        )

    # Intermediate terms (359)
    _tmp0 = math.exp(theta_pos[2, 0])
    _tmp1 = p[0, 0] - p_d[0, 0]
    _tmp2 = _tmp0 * _tmp1
    _tmp3 = math.exp(theta_pos[4, 0])
    _tmp4 = v[0, 0] - v_d[0, 0]
    _tmp5 = _tmp3 * _tmp4
    _tmp6 = math.exp(theta_pos[0, 0])
    _tmp7 = _tmp6 * ierr[0, 0]
    _tmp8 = -_tmp2 - _tmp5 - _tmp7 + a_d[0, 0]
    _tmp9 = logR[0, 0] ** 2
    _tmp10 = logR[2, 0] ** 2
    _tmp11 = logR[1, 0] ** 2
    _tmp12 = _tmp10 + _tmp11 + _tmp9 + 1.0e-12
    _tmp13 = 1 / _tmp12
    _tmp14 = math.sqrt(_tmp12)
    _tmp15 = (1.0 / 2.0) * _tmp14
    _tmp16 = math.sin(_tmp15)
    _tmp17 = _tmp16**2
    _tmp18 = _tmp13 * _tmp17
    _tmp19 = _tmp18 * logR[0, 0]
    _tmp20 = 2 * logR[2, 0]
    _tmp21 = _tmp16 / _tmp14
    _tmp22 = _tmp21 * logR[1, 0]
    _tmp23 = math.cos(_tmp15)
    _tmp24 = 2 * _tmp23
    _tmp25 = _tmp19 * _tmp20 + _tmp22 * _tmp24
    _tmp26 = _tmp11 * _tmp13
    _tmp27 = _tmp17 * _tmp26
    _tmp28 = _tmp13 * _tmp9
    _tmp29 = _tmp17 * _tmp28
    _tmp30 = -2 * _tmp27 - 2 * _tmp29 + 1
    _tmp31 = math.exp(theta_pos[3, 0])
    _tmp32 = _tmp31 * (p[2, 0] - p_d[2, 0])
    _tmp33 = math.exp(theta_pos[5, 0])
    _tmp34 = _tmp33 * (v[2, 0] - v_d[2, 0])
    _tmp35 = math.exp(theta_pos[1, 0])
    _tmp36 = _tmp35 * ierr[2, 0]
    _tmp37 = -_tmp32 - _tmp34 - _tmp36 + a_d[2, 0] + 9.81
    _tmp38 = _tmp0 * (p[1, 0] - p_d[1, 0])
    _tmp39 = _tmp3 * (v[1, 0] - v_d[1, 0])
    _tmp40 = _tmp6 * ierr[1, 0]
    _tmp41 = -_tmp38 - _tmp39 - _tmp40 + a_d[1, 0]
    _tmp42 = _tmp18 * logR[1, 0]
    _tmp43 = 2 * _tmp42
    _tmp44 = _tmp21 * _tmp24
    _tmp45 = _tmp43 * logR[2, 0] - _tmp44 * logR[0, 0]
    _tmp46 = _tmp37**2
    _tmp47 = _tmp41**2
    _tmp48 = _tmp8**2
    _tmp49 = _tmp46 + _tmp47 + _tmp48 + 1.0e-6
    _tmp50 = 1 / math.sqrt(_tmp49)
    _tmp51 = _tmp37 * _tmp50
    _tmp52 = 2 * _tmp51 + 2.000001
    _tmp53 = math.sqrt(_tmp52)
    _tmp54 = 1 / _tmp53
    _tmp55 = (
        0.0 if abs(_tmp51 + 1) - 1.0e-6 == 0 else math.copysign(1, abs(_tmp51 + 1) - 1.0e-6)
    ) + 1
    _tmp56 = (1.0 / 2.0) * _tmp55
    _tmp57 = _tmp54 * _tmp56
    _tmp58 = _tmp50 * _tmp57
    _tmp59 = -_tmp41 * _tmp58 - _tmp56 + 1
    _tmp60 = _tmp23 * _tmp59
    _tmp61 = _tmp21 * logR[2, 0]
    _tmp62 = _tmp58 * _tmp8
    _tmp63 = _tmp21 * logR[0, 0]
    _tmp64 = (1.0 / 4.0) * _tmp53
    _tmp65 = _tmp55 * _tmp64
    _tmp66 = -_tmp60 + _tmp61 * _tmp62 + _tmp63 * _tmp65
    _tmp67 = math.exp(theta_rot[0, 0])
    _tmp68 = _tmp22 * _tmp62
    _tmp69 = _tmp21 * _tmp59
    _tmp70 = _tmp69 * logR[0, 0]
    _tmp71 = -_tmp68 - _tmp70
    _tmp72 = _tmp23 * _tmp55
    _tmp73 = _tmp64 * _tmp72
    _tmp74 = 2 * min(0, (0.0 if -_tmp71 + _tmp73 == 0 else math.copysign(1, -_tmp71 + _tmp73))) + 1
    _tmp75 = 2 * _tmp74
    _tmp76 = _tmp67 * _tmp75
    _tmp77 = min(0.999999, abs(_tmp71 - _tmp73))
    _tmp78 = math.acos(_tmp77) / math.sqrt(1 - _tmp77**2)
    _tmp79 = _tmp76 * _tmp78
    _tmp80 = math.exp(theta_rot[2, 0])
    _tmp81 = _tmp80 * (w[0, 0] - w_d[0, 0])
    _tmp82 = -_tmp81
    _tmp83 = _tmp69 * logR[2, 0]
    _tmp84 = _tmp22 * _tmp65 - _tmp23 * _tmp62 - _tmp83
    _tmp85 = w[1, 0] - w_d[1, 0]
    _tmp86 = -_tmp80 * _tmp85
    _tmp87 = _tmp69 * logR[1, 0]
    _tmp88 = _tmp61 * _tmp65 - _tmp62 * _tmp63 + _tmp87
    _tmp89 = math.exp(theta_rot[1, 0])
    _tmp90 = _tmp75 * _tmp89
    _tmp91 = math.exp(theta_rot[3, 0])
    _tmp92 = w[2, 0] - w_d[2, 0]
    _tmp93 = -_tmp91 * _tmp92
    _tmp94 = _tmp25 * _tmp6
    _tmp95 = _tmp49 ** (-3.0 / 2.0)
    _tmp96 = _tmp72 * _tmp8
    _tmp97 = _tmp54 * _tmp96
    _tmp98 = _tmp95 * _tmp97
    _tmp99 = (1.0 / 4.0) * _tmp98
    _tmp100 = _tmp37 * _tmp6
    _tmp101 = _tmp52 ** (-3.0 / 2.0)
    _tmp102 = _tmp37 / _tmp49**2
    _tmp103 = _tmp101 * _tmp102
    _tmp104 = _tmp103 * _tmp56
    _tmp105 = _tmp104 * _tmp48
    _tmp106 = _tmp105 * _tmp6
    _tmp107 = _tmp58 * _tmp6
    _tmp108 = _tmp6 * _tmp8
    _tmp109 = _tmp104 * _tmp41
    _tmp110 = _tmp108 * _tmp109
    _tmp111 = _tmp41 * _tmp95
    _tmp112 = _tmp111 * _tmp57
    _tmp113 = _tmp108 * _tmp112
    _tmp114 = _tmp110 - _tmp113
    _tmp115 = _tmp57 * _tmp95
    _tmp116 = _tmp115 * _tmp48
    _tmp117 = _tmp116 * _tmp22
    _tmp118 = (
        _tmp100 * _tmp99 - _tmp106 * _tmp22 - _tmp107 * _tmp22 + _tmp114 * _tmp63 + _tmp117 * _tmp6
    )
    _tmp119 = _tmp68 + _tmp70 + _tmp73
    _tmp120 = abs(_tmp119)
    _tmp121 = min(0.999999, _tmp120)
    _tmp122 = 1 - _tmp121**2
    _tmp123 = (
        _tmp74
        * ((0.0 if 0.999999 - _tmp120 == 0 else math.copysign(1, 0.999999 - _tmp120)) + 1)
        * (0.0 if _tmp119 == 0 else math.copysign(1, _tmp119))
    )
    _tmp124 = _tmp123 / _tmp122
    _tmp125 = _tmp124 * _tmp67
    _tmp126 = _tmp125 * _tmp66
    _tmp127 = math.acos(_tmp121)
    _tmp128 = _tmp121 * _tmp123 * _tmp127 / _tmp122 ** (3.0 / 2.0)
    _tmp129 = _tmp66 * _tmp67
    _tmp130 = _tmp128 * _tmp129
    _tmp131 = _tmp54 * _tmp55
    _tmp132 = _tmp37 * _tmp95
    _tmp133 = (1.0 / 4.0) * _tmp108 * _tmp131 * _tmp132
    _tmp134 = _tmp116 * _tmp61
    _tmp135 = _tmp127 / math.sqrt(_tmp122)
    _tmp136 = _tmp135 * _tmp76
    _tmp137 = _tmp136 * _tmp66
    _tmp138 = 1 - math.tanh((1.0 / 268.0) * _tmp137 - 1.0 / 268.0 * _tmp82) ** 2
    _tmp139 = _tmp116 * _tmp23
    _tmp140 = _tmp105 * _tmp23
    _tmp141 = _tmp118 * _tmp128
    _tmp142 = _tmp67 * _tmp84
    _tmp143 = _tmp125 * _tmp84
    _tmp144 = _tmp136 * _tmp84
    _tmp145 = 1 - math.tanh((1.0 / 268.0) * _tmp144 - 1.0 / 268.0 * _tmp86) ** 2
    _tmp146 = _tmp88 * _tmp89
    _tmp147 = _tmp124 * _tmp146
    _tmp148 = _tmp116 * _tmp63
    _tmp149 = _tmp135 * _tmp90
    _tmp150 = _tmp149 * _tmp88
    _tmp151 = 1 - math.tanh((1.0 / 56.0) * _tmp150 - 1.0 / 56.0 * _tmp93) ** 2
    _tmp152 = _tmp45 * _tmp6
    _tmp153 = _tmp104 * _tmp47
    _tmp154 = _tmp115 * _tmp47
    _tmp155 = _tmp107 + _tmp153 * _tmp6 - _tmp154 * _tmp6
    _tmp156 = _tmp111 * _tmp54 * _tmp72
    _tmp157 = (1.0 / 4.0) * _tmp156
    _tmp158 = _tmp100 * _tmp157 - _tmp110 * _tmp22 + _tmp113 * _tmp22 + _tmp155 * _tmp63
    _tmp159 = _tmp111 * _tmp131
    _tmp160 = (1.0 / 4.0) * _tmp159
    _tmp161 = _tmp160 * _tmp63
    _tmp162 = _tmp128 * _tmp142
    _tmp163 = _tmp128 * _tmp146
    _tmp164 = _tmp160 * _tmp61
    _tmp165 = _tmp30 * _tmp35
    _tmp166 = _tmp37 * _tmp57
    _tmp167 = _tmp111 * _tmp166
    _tmp168 = 2 * _tmp50
    _tmp169 = 2 * _tmp46
    _tmp170 = _tmp169 * _tmp95
    _tmp171 = -_tmp168 * _tmp35 + _tmp170 * _tmp35
    _tmp172 = (1.0 / 4.0) * _tmp101
    _tmp173 = _tmp172 * _tmp50
    _tmp174 = _tmp41 * _tmp55
    _tmp175 = _tmp173 * _tmp174
    _tmp176 = -_tmp167 * _tmp35 + _tmp171 * _tmp175
    _tmp177 = _tmp115 * _tmp37
    _tmp178 = _tmp177 * _tmp8
    _tmp179 = _tmp178 * _tmp35
    _tmp180 = (1.0 / 8.0) * _tmp72
    _tmp181 = _tmp180 * _tmp54
    _tmp182 = _tmp55 * _tmp8
    _tmp183 = _tmp173 * _tmp182
    _tmp184 = _tmp183 * _tmp22
    _tmp185 = _tmp171 * _tmp181 - _tmp171 * _tmp184 + _tmp176 * _tmp63 + _tmp179 * _tmp22
    _tmp186 = _tmp171 * _tmp61
    _tmp187 = (1.0 / 8.0) * _tmp131
    _tmp188 = _tmp187 * _tmp63
    _tmp189 = _tmp23 * _tmp8
    _tmp190 = _tmp177 * _tmp189
    _tmp191 = (1.0 / 8.0) * _tmp22
    _tmp192 = _tmp131 * _tmp191
    _tmp193 = _tmp173 * _tmp96
    _tmp194 = _tmp183 * _tmp63
    _tmp195 = _tmp0 * _tmp25
    _tmp196 = _tmp0 * _tmp37
    _tmp197 = _tmp0 * _tmp58
    _tmp198 = _tmp0 * _tmp105
    _tmp199 = _tmp112 * _tmp8
    _tmp200 = _tmp0 * _tmp199
    _tmp201 = _tmp109 * _tmp8
    _tmp202 = _tmp0 * _tmp201
    _tmp203 = -_tmp200 + _tmp202
    _tmp204 = (
        _tmp0 * _tmp117 + _tmp196 * _tmp99 - _tmp197 * _tmp22 - _tmp198 * _tmp22 + _tmp203 * _tmp63
    )
    _tmp205 = _tmp125 * _tmp204
    _tmp206 = _tmp131 * _tmp8
    _tmp207 = _tmp206 * _tmp95
    _tmp208 = (1.0 / 4.0) * _tmp207
    _tmp209 = _tmp196 * _tmp208
    _tmp210 = _tmp196 * _tmp22
    _tmp211 = _tmp0 * _tmp23
    _tmp212 = _tmp0 * _tmp153 - _tmp0 * _tmp154 + _tmp197
    _tmp213 = _tmp157 * _tmp196 + _tmp200 * _tmp22 - _tmp202 * _tmp22 + _tmp212 * _tmp63
    _tmp214 = -_tmp168 * _tmp31 + _tmp170 * _tmp31
    _tmp215 = -_tmp167 * _tmp31 + _tmp175 * _tmp214
    _tmp216 = _tmp178 * _tmp31
    _tmp217 = _tmp181 * _tmp214 - _tmp184 * _tmp214 + _tmp215 * _tmp63 + _tmp216 * _tmp22
    _tmp218 = _tmp183 * _tmp61
    _tmp219 = _tmp187 * _tmp61
    _tmp220 = _tmp25 * _tmp3
    _tmp221 = _tmp3 * _tmp58
    _tmp222 = _tmp105 * _tmp3
    _tmp223 = _tmp201 * _tmp3
    _tmp224 = _tmp199 * _tmp3
    _tmp225 = _tmp223 - _tmp224
    _tmp226 = _tmp3 * _tmp37
    _tmp227 = (
        _tmp117 * _tmp3 - _tmp22 * _tmp221 - _tmp22 * _tmp222 + _tmp225 * _tmp63 + _tmp226 * _tmp99
    )
    _tmp228 = (1.0 / 4.0) * _tmp226
    _tmp229 = _tmp207 * _tmp228
    _tmp230 = _tmp160 * _tmp226
    _tmp231 = _tmp3 * _tmp47
    _tmp232 = _tmp104 * _tmp231 - _tmp115 * _tmp231 + _tmp221
    _tmp233 = _tmp156 * _tmp228 - _tmp22 * _tmp223 + _tmp22 * _tmp224 + _tmp232 * _tmp63
    _tmp234 = _tmp33 * _tmp95
    _tmp235 = _tmp166 * _tmp234
    _tmp236 = -_tmp168 * _tmp33 + _tmp169 * _tmp234
    _tmp237 = _tmp175 * _tmp236 - _tmp235 * _tmp41
    _tmp238 = _tmp235 * _tmp8
    _tmp239 = _tmp21 * _tmp237
    _tmp240 = _tmp181 * _tmp236 - _tmp184 * _tmp236 + _tmp22 * _tmp238 + _tmp239 * logR[0, 0]
    _tmp241 = _tmp23**2
    _tmp242 = _tmp16 / _tmp12 ** (3.0 / 2.0)
    _tmp243 = _tmp24 * _tmp242
    _tmp244 = _tmp243 * _tmp9
    _tmp245 = logR[0, 0] * logR[2, 0]
    _tmp246 = 4 * _tmp17 / _tmp12**2
    _tmp247 = _tmp246 * logR[1, 0]
    _tmp248 = _tmp243 * _tmp245
    _tmp249 = -_tmp245 * _tmp247 + _tmp248 * logR[1, 0]
    _tmp250 = _tmp246 * logR[0, 0]
    _tmp251 = logR[0, 0] ** 3
    _tmp252 = _tmp11 * _tmp243
    _tmp253 = _tmp244 * logR[2, 0]
    _tmp254 = _tmp13 * _tmp241
    _tmp255 = _tmp254 * logR[1, 0]
    _tmp256 = _tmp255 * logR[0, 0]
    _tmp257 = _tmp42 * logR[0, 0]
    _tmp258 = _tmp246 * logR[2, 0]
    _tmp259 = _tmp258 * _tmp9
    _tmp260 = _tmp18 * _tmp20
    _tmp261 = _tmp243 * logR[1, 0]
    _tmp262 = _tmp261 * logR[0, 0]
    _tmp263 = (1.0 / 4.0) * _tmp50
    _tmp264 = _tmp263 * _tmp97
    _tmp265 = _tmp13 * _tmp264
    _tmp266 = _tmp245 * _tmp265
    _tmp267 = _tmp242 * _tmp65
    _tmp268 = _tmp21 * _tmp65
    _tmp269 = _tmp180 * _tmp53
    _tmp270 = _tmp242 * _tmp62
    _tmp271 = _tmp245 * _tmp270
    _tmp272 = logR[0, 0] * logR[1, 0]
    _tmp273 = _tmp265 * _tmp272
    _tmp274 = (1.0 / 2.0) * _tmp60
    _tmp275 = _tmp53 * _tmp55
    _tmp276 = (1.0 / 8.0) * _tmp275
    _tmp277 = _tmp270 * _tmp272
    _tmp278 = _tmp242 * _tmp59
    _tmp279 = _tmp273 + _tmp274 * _tmp28 - _tmp276 * _tmp63 - _tmp277 - _tmp278 * _tmp9 + _tmp69
    _tmp280 = _tmp13 * _tmp274
    _tmp281 = _tmp245 * _tmp280
    _tmp282 = _tmp245 * _tmp278
    _tmp283 = _tmp206 * _tmp263
    _tmp284 = _tmp13 * _tmp269
    _tmp285 = -_tmp267 * _tmp272 + _tmp272 * _tmp284
    _tmp286 = _tmp21 * _tmp62
    _tmp287 = -_tmp245 * _tmp267 + _tmp245 * _tmp284
    _tmp288 = _tmp278 * logR[1, 0]
    _tmp289 = _tmp280 * logR[1, 0]
    _tmp290 = -_tmp288 * logR[0, 0] + _tmp289 * logR[0, 0]
    _tmp291 = _tmp11 * _tmp258
    _tmp292 = _tmp252 * logR[2, 0]
    _tmp293 = logR[1, 0] ** 3
    _tmp294 = -_tmp11 * _tmp270 - _tmp191 * _tmp275 + _tmp26 * _tmp264 + _tmp286 + _tmp290
    _tmp295 = logR[1, 0] * logR[2, 0]
    _tmp296 = _tmp265 * _tmp295 - _tmp270 * _tmp295
    _tmp297 = _tmp288 * logR[2, 0]
    _tmp298 = _tmp289 * logR[2, 0]
    _tmp299 = -_tmp267 * _tmp295 + _tmp284 * _tmp295
    _tmp300 = -_tmp276 * _tmp61 + _tmp281 - _tmp282 + _tmp296
    _tmp301 = _tmp128 * _tmp300
    _tmp302 = _tmp145 * _tmp80
    _tmp303 = _tmp151 * _tmp91
    _tmp304 = 2 * _tmp8
    _tmp305 = 2 * _tmp41
    _tmp306 = -_tmp304 * _tmp7 - _tmp305 * _tmp40
    _tmp307 = _tmp102 * _tmp174
    _tmp308 = _tmp172 * _tmp307
    _tmp309 = _tmp160 * _tmp306 - _tmp306 * _tmp308 + _tmp40 * _tmp58
    _tmp310 = _tmp182 * _tmp22
    _tmp311 = _tmp102 * _tmp172
    _tmp312 = _tmp306 * _tmp311
    _tmp313 = _tmp22 * _tmp58
    _tmp314 = _tmp306 * _tmp95
    _tmp315 = _tmp181 * _tmp37
    _tmp316 = (1.0 / 4.0) * _tmp314
    _tmp317 = _tmp206 * _tmp316
    _tmp318 = (
        -_tmp22 * _tmp317
        + _tmp309 * _tmp63
        + _tmp310 * _tmp312
        - _tmp313 * _tmp7
        - _tmp314 * _tmp315
    )
    _tmp319 = _tmp182 * _tmp61
    _tmp320 = _tmp314 * _tmp37
    _tmp321 = _tmp58 * _tmp61
    _tmp322 = _tmp23 * _tmp58
    _tmp323 = _tmp311 * _tmp96
    _tmp324 = _tmp182 * _tmp63
    _tmp325 = _tmp58 * _tmp63
    _tmp326 = _tmp178 * _tmp36
    _tmp327 = -_tmp168 * _tmp36 + _tmp170 * _tmp36
    _tmp328 = -_tmp167 * _tmp36 + _tmp175 * _tmp327
    _tmp329 = _tmp181 * _tmp327 - _tmp184 * _tmp327 + _tmp22 * _tmp326 + _tmp328 * _tmp63
    _tmp330 = _tmp183 * _tmp327
    _tmp331 = _tmp178 * _tmp63
    _tmp332 = -_tmp2 * _tmp304 - _tmp305 * _tmp38
    _tmp333 = (1.0 / 4.0) * _tmp332
    _tmp334 = _tmp103 * _tmp333
    _tmp335 = -_tmp101 * _tmp307 * _tmp333 + _tmp159 * _tmp333 + _tmp38 * _tmp58
    _tmp336 = _tmp207 * _tmp333
    _tmp337 = _tmp132 * _tmp332
    _tmp338 = _tmp315 * _tmp95
    _tmp339 = (
        -_tmp2 * _tmp313
        - _tmp22 * _tmp336
        + _tmp310 * _tmp334
        - _tmp332 * _tmp338
        + _tmp335 * _tmp63
    )
    _tmp340 = -_tmp168 * _tmp32 + _tmp170 * _tmp32
    _tmp341 = _tmp178 * _tmp32
    _tmp342 = _tmp173 * _tmp340
    _tmp343 = _tmp182 * _tmp342
    _tmp344 = -_tmp167 * _tmp32 + _tmp174 * _tmp342
    _tmp345 = _tmp21 * _tmp344
    _tmp346 = _tmp181 * _tmp340 + _tmp22 * _tmp341 - _tmp22 * _tmp343 + _tmp345 * logR[0, 0]
    _tmp347 = _tmp5 * _tmp58
    _tmp348 = -_tmp304 * _tmp5 - _tmp305 * _tmp39
    _tmp349 = _tmp311 * _tmp348
    _tmp350 = _tmp160 * _tmp348 - _tmp308 * _tmp348 + _tmp39 * _tmp58
    _tmp351 = _tmp208 * _tmp348
    _tmp352 = (
        -_tmp22 * _tmp347
        - _tmp22 * _tmp351
        + _tmp310 * _tmp349
        - _tmp338 * _tmp348
        + _tmp350 * _tmp63
    )
    _tmp353 = _tmp132 * _tmp348
    _tmp354 = _tmp348 * _tmp61
    _tmp355 = _tmp178 * _tmp34
    _tmp356 = -_tmp168 * _tmp34 + _tmp170 * _tmp34
    _tmp357 = -_tmp167 * _tmp34 + _tmp175 * _tmp356
    _tmp358 = _tmp181 * _tmp356 - _tmp184 * _tmp356 + _tmp22 * _tmp355 + _tmp357 * _tmp63

    # Output terms
    _thrust_torque = numpy.zeros(4)
    _thrust_torque[0] = _tmp25 * _tmp8 + _tmp30 * _tmp37 + _tmp41 * _tmp45
    _thrust_torque[1] = -268 * math.tanh((1.0 / 268.0) * _tmp66 * _tmp79 - 1.0 / 268.0 * _tmp82)
    _thrust_torque[2] = -268 * math.tanh((1.0 / 268.0) * _tmp79 * _tmp84 - 1.0 / 268.0 * _tmp86)
    _thrust_torque[3] = -56 * math.tanh(
        (1.0 / 56.0) * _tmp78 * _tmp88 * _tmp90 - 1.0 / 56.0 * _tmp93
    )
    _jacobian = numpy.zeros((4, 25))
    _jacobian[0, 0] = -_tmp94
    _jacobian[1, 0] = _tmp138 * (
        _tmp118 * _tmp126
        - _tmp118 * _tmp130
        - _tmp136
        * (
            -_tmp106 * _tmp61
            - _tmp107 * _tmp61
            - _tmp114 * _tmp23
            + _tmp133 * _tmp63
            + _tmp134 * _tmp6
        )
    )
    _jacobian[2, 0] = _tmp145 * (
        _tmp118 * _tmp143
        - _tmp136
        * (
            _tmp107 * _tmp23
            - _tmp114 * _tmp61
            + _tmp133 * _tmp22
            - _tmp139 * _tmp6
            + _tmp140 * _tmp6
        )
        - _tmp141 * _tmp142
    )
    _jacobian[3, 0] = _tmp151 * (
        _tmp118 * _tmp147
        - _tmp141 * _tmp146
        - _tmp149
        * (
            _tmp106 * _tmp63
            + _tmp107 * _tmp63
            + _tmp114 * _tmp22
            + _tmp133 * _tmp61
            - _tmp148 * _tmp6
        )
    )
    _jacobian[0, 1] = -_tmp152
    _jacobian[1, 1] = _tmp138 * (
        _tmp126 * _tmp158
        - _tmp130 * _tmp158
        - _tmp136 * (_tmp100 * _tmp161 - _tmp110 * _tmp61 + _tmp113 * _tmp61 - _tmp155 * _tmp23)
    )
    _jacobian[2, 1] = _tmp145 * (
        -_tmp136
        * (_tmp100 * _tmp160 * _tmp22 + _tmp110 * _tmp23 - _tmp113 * _tmp23 - _tmp155 * _tmp61)
        + _tmp143 * _tmp158
        - _tmp158 * _tmp162
    )
    _jacobian[3, 1] = _tmp151 * (
        _tmp147 * _tmp158
        - _tmp149 * (_tmp100 * _tmp164 + _tmp110 * _tmp63 - _tmp113 * _tmp63 + _tmp155 * _tmp22)
        - _tmp158 * _tmp163
    )
    _jacobian[0, 2] = -_tmp165
    _jacobian[1, 2] = _tmp138 * (
        _tmp126 * _tmp185
        - _tmp130 * _tmp185
        - _tmp136 * (_tmp171 * _tmp188 - _tmp176 * _tmp23 + _tmp179 * _tmp61 - _tmp183 * _tmp186)
    )
    _jacobian[2, 2] = _tmp145 * (
        -_tmp136 * (_tmp171 * _tmp192 + _tmp171 * _tmp193 - _tmp176 * _tmp61 - _tmp190 * _tmp35)
        + _tmp143 * _tmp185
        - _tmp162 * _tmp185
    )
    _jacobian[3, 2] = _tmp151 * (
        _tmp147 * _tmp185
        - _tmp149 * (_tmp171 * _tmp194 + _tmp176 * _tmp22 - _tmp179 * _tmp63 + _tmp186 * _tmp187)
        - _tmp163 * _tmp185
    )
    _jacobian[0, 3] = -_tmp195
    _jacobian[1, 3] = _tmp138 * (
        -_tmp130 * _tmp204
        - _tmp136
        * (
            _tmp0 * _tmp134
            - _tmp197 * _tmp61
            - _tmp198 * _tmp61
            - _tmp203 * _tmp23
            + _tmp209 * _tmp63
        )
        + _tmp205 * _tmp66
    )
    _jacobian[2, 3] = _tmp145 * (
        -_tmp136
        * (
            _tmp105 * _tmp211
            - _tmp116 * _tmp211
            + _tmp197 * _tmp23
            - _tmp203 * _tmp61
            + _tmp208 * _tmp210
        )
        - _tmp162 * _tmp204
        + _tmp205 * _tmp84
    )
    _jacobian[3, 3] = _tmp151 * (
        _tmp147 * _tmp204
        - _tmp149
        * (
            -_tmp0 * _tmp148
            + _tmp197 * _tmp63
            + _tmp198 * _tmp63
            + _tmp203 * _tmp22
            + _tmp209 * _tmp61
        )
        - _tmp163 * _tmp204
    )
    _jacobian[0, 4] = -_tmp0 * _tmp45
    _jacobian[1, 4] = _tmp138 * (
        _tmp126 * _tmp213
        - _tmp130 * _tmp213
        - _tmp136 * (_tmp161 * _tmp196 + _tmp200 * _tmp61 - _tmp202 * _tmp61 - _tmp212 * _tmp23)
    )
    _jacobian[2, 4] = _tmp145 * (
        -_tmp136 * (_tmp160 * _tmp210 - _tmp199 * _tmp211 + _tmp201 * _tmp211 - _tmp212 * _tmp61)
        + _tmp143 * _tmp213
        - _tmp162 * _tmp213
    )
    _jacobian[3, 4] = _tmp151 * (
        _tmp147 * _tmp213
        - _tmp149 * (_tmp164 * _tmp196 - _tmp200 * _tmp63 + _tmp202 * _tmp63 + _tmp212 * _tmp22)
        - _tmp163 * _tmp213
    )
    _jacobian[0, 5] = -_tmp30 * _tmp31
    _jacobian[1, 5] = _tmp138 * (
        _tmp126 * _tmp217
        - _tmp130 * _tmp217
        - _tmp136 * (_tmp188 * _tmp214 - _tmp214 * _tmp218 - _tmp215 * _tmp23 + _tmp216 * _tmp61)
    )
    _jacobian[2, 5] = _tmp145 * (
        -_tmp136 * (-_tmp190 * _tmp31 + _tmp192 * _tmp214 + _tmp193 * _tmp214 - _tmp215 * _tmp61)
        + _tmp143 * _tmp217
        - _tmp162 * _tmp217
    )
    _jacobian[3, 5] = _tmp151 * (
        _tmp147 * _tmp217
        - _tmp149 * (_tmp194 * _tmp214 + _tmp214 * _tmp219 + _tmp215 * _tmp22 - _tmp216 * _tmp63)
        - _tmp163 * _tmp217
    )
    _jacobian[0, 6] = -_tmp220
    _jacobian[1, 6] = _tmp138 * (
        _tmp126 * _tmp227
        - _tmp130 * _tmp227
        - _tmp136
        * (
            _tmp134 * _tmp3
            - _tmp221 * _tmp61
            - _tmp222 * _tmp61
            - _tmp225 * _tmp23
            + _tmp229 * _tmp63
        )
    )
    _jacobian[2, 6] = _tmp145 * (
        -_tmp136
        * (
            -_tmp139 * _tmp3
            + _tmp140 * _tmp3
            + _tmp22 * _tmp229
            + _tmp221 * _tmp23
            - _tmp225 * _tmp61
        )
        + _tmp143 * _tmp227
        - _tmp162 * _tmp227
    )
    _jacobian[3, 6] = _tmp151 * (
        _tmp147 * _tmp227
        - _tmp149
        * (
            -_tmp148 * _tmp3
            + _tmp22 * _tmp225
            + _tmp221 * _tmp63
            + _tmp222 * _tmp63
            + _tmp229 * _tmp61
        )
        - _tmp163 * _tmp227
    )
    _jacobian[0, 7] = -_tmp3 * _tmp45
    _jacobian[1, 7] = _tmp138 * (
        _tmp126 * _tmp233
        - _tmp130 * _tmp233
        - _tmp136 * (-_tmp223 * _tmp61 + _tmp224 * _tmp61 - _tmp23 * _tmp232 + _tmp230 * _tmp63)
    )
    _jacobian[2, 7] = _tmp145 * (
        -_tmp136
        * (_tmp109 * _tmp189 * _tmp3 + _tmp22 * _tmp230 - _tmp224 * _tmp23 - _tmp232 * _tmp61)
        + _tmp143 * _tmp233
        - _tmp162 * _tmp233
    )
    _jacobian[3, 7] = _tmp151 * (
        _tmp147 * _tmp233
        - _tmp149 * (_tmp164 * _tmp226 + _tmp22 * _tmp232 + _tmp223 * _tmp63 - _tmp224 * _tmp63)
        - _tmp163 * _tmp233
    )
    _jacobian[0, 8] = -_tmp30 * _tmp33
    _jacobian[1, 8] = _tmp138 * (
        _tmp126 * _tmp240
        - _tmp130 * _tmp240
        - _tmp136 * (_tmp188 * _tmp236 - _tmp218 * _tmp236 - _tmp23 * _tmp237 + _tmp238 * _tmp61)
    )
    _jacobian[2, 8] = _tmp145 * (
        -_tmp136
        * (-_tmp189 * _tmp235 + _tmp192 * _tmp236 + _tmp193 * _tmp236 - _tmp239 * logR[2, 0])
        + _tmp143 * _tmp240
        - _tmp162 * _tmp240
    )
    _jacobian[3, 8] = _tmp151 * (
        _tmp147 * _tmp240
        - _tmp149
        * (_tmp194 * _tmp236 + _tmp219 * _tmp236 - _tmp238 * _tmp63 + _tmp239 * logR[1, 0])
        - _tmp163 * _tmp240
    )
    _jacobian[0, 9] = (
        _tmp37
        * (
            _tmp11 * _tmp250
            - 4 * _tmp19
            - _tmp243 * _tmp251
            + _tmp246 * _tmp251
            - _tmp252 * logR[0, 0]
        )
        + _tmp41 * (-_tmp241 * _tmp28 + _tmp244 + _tmp249 + _tmp29 - _tmp44)
        + _tmp8 * (_tmp253 + _tmp256 - _tmp257 - _tmp259 + _tmp260 - _tmp262)
    )
    _jacobian[1, 9] = _tmp138 * (
        _tmp126 * _tmp279
        - _tmp130 * _tmp279
        - _tmp136
        * (_tmp266 - _tmp267 * _tmp9 + _tmp268 + _tmp269 * _tmp28 - _tmp271 + (1.0 / 2.0) * _tmp70)
    )
    _jacobian[2, 9] = _tmp145 * (
        -_tmp136 * (-_tmp281 + _tmp282 + _tmp283 * _tmp63 + _tmp285)
        + _tmp143 * _tmp279
        - _tmp162 * _tmp279
    )
    _jacobian[3, 9] = _tmp151 * (
        _tmp147 * _tmp279
        - _tmp149 * (-_tmp264 * _tmp28 + _tmp270 * _tmp9 - _tmp286 + _tmp287 + _tmp290)
        - _tmp163 * _tmp279
    )
    _jacobian[0, 10] = (
        _tmp37
        * (
            -_tmp243 * _tmp293
            - _tmp244 * logR[1, 0]
            + _tmp246 * _tmp293
            + _tmp247 * _tmp9
            - 4 * _tmp42
        )
        + _tmp41 * (-_tmp256 + _tmp257 + _tmp260 + _tmp262 - _tmp291 + _tmp292)
        + _tmp8 * (_tmp241 * _tmp26 + _tmp249 - _tmp252 - _tmp27 + _tmp44)
    )
    _jacobian[1, 10] = _tmp138 * (
        _tmp126 * _tmp294 - _tmp130 * _tmp294 - _tmp136 * (_tmp285 + _tmp296 + (1.0 / 2.0) * _tmp87)
    )
    _jacobian[2, 10] = _tmp145 * (
        -_tmp136
        * (-_tmp11 * _tmp267 + _tmp22 * _tmp283 + _tmp26 * _tmp269 + _tmp268 + _tmp297 - _tmp298)
        + _tmp143 * _tmp294
        - _tmp162 * _tmp294
    )
    _jacobian[3, 10] = _tmp151 * (
        _tmp147 * _tmp294
        - _tmp149 * (-_tmp11 * _tmp278 + _tmp26 * _tmp274 - _tmp273 + _tmp277 + _tmp299 + _tmp69)
        - _tmp163 * _tmp294
    )
    _jacobian[0, 11] = (
        _tmp37 * (-_tmp253 + _tmp259 + _tmp291 - _tmp292)
        + _tmp41
        * (
            -_tmp10 * _tmp247
            + _tmp10 * _tmp261
            + _tmp19 * logR[2, 0]
            - _tmp245 * _tmp254
            + _tmp248
            + _tmp43
        )
        + _tmp8
        * (
            _tmp10 * _tmp243 * logR[0, 0]
            - _tmp10 * _tmp250
            + 2 * _tmp19
            + _tmp255 * logR[2, 0]
            - _tmp261 * logR[2, 0]
            - _tmp42 * logR[2, 0]
        )
    )
    _jacobian[1, 11] = _tmp138 * (
        _tmp126 * _tmp300
        - _tmp129 * _tmp301
        - _tmp136 * (_tmp10 * _tmp265 - _tmp10 * _tmp270 + _tmp286 + _tmp287 + (1.0 / 2.0) * _tmp83)
    )
    _jacobian[2, 11] = _tmp145 * (
        -_tmp136 * (_tmp10 * _tmp278 - _tmp10 * _tmp280 + _tmp283 * _tmp61 + _tmp299 - _tmp69)
        - _tmp142 * _tmp301
        + _tmp143 * _tmp300
    )
    _jacobian[3, 11] = _tmp151 * (
        -_tmp146 * _tmp301
        + _tmp147 * _tmp300
        - _tmp149
        * (-_tmp10 * _tmp267 + _tmp10 * _tmp284 - _tmp266 + _tmp268 + _tmp271 - _tmp297 + _tmp298)
    )
    _jacobian[0, 12] = 0
    _jacobian[1, 12] = -_tmp138 * _tmp80
    _jacobian[2, 12] = 0
    _jacobian[3, 12] = 0
    _jacobian[0, 13] = 0
    _jacobian[1, 13] = 0
    _jacobian[2, 13] = -_tmp302
    _jacobian[3, 13] = 0
    _jacobian[0, 14] = 0
    _jacobian[1, 14] = 0
    _jacobian[2, 14] = 0
    _jacobian[3, 14] = -_tmp303
    _jacobian[0, 15] = -_tmp152 * ierr[1, 0] - _tmp94 * ierr[0, 0]
    _jacobian[1, 15] = _tmp138 * (
        _tmp126 * _tmp318
        - _tmp130 * _tmp318
        - _tmp136
        * (
            -_tmp188 * _tmp320
            - _tmp23 * _tmp309
            + _tmp312 * _tmp319
            - _tmp317 * _tmp61
            - _tmp321 * _tmp7
        )
    )
    _jacobian[2, 15] = _tmp145 * (
        -_tmp136
        * (
            -_tmp192 * _tmp320
            - _tmp306 * _tmp323
            - _tmp309 * _tmp61
            + _tmp316 * _tmp97
            + _tmp322 * _tmp7
        )
        + _tmp143 * _tmp318
        - _tmp162 * _tmp318
    )
    _jacobian[3, 15] = _tmp151 * (
        _tmp147 * _tmp318
        - _tmp149
        * (
            -_tmp219 * _tmp320
            + _tmp22 * _tmp309
            - _tmp312 * _tmp324
            + _tmp317 * _tmp63
            + _tmp325 * _tmp7
        )
        - _tmp163 * _tmp318
    )
    _jacobian[0, 16] = -_tmp165 * ierr[2, 0]
    _jacobian[1, 16] = _tmp138 * (
        _tmp126 * _tmp329
        - _tmp130 * _tmp329
        - _tmp136 * (_tmp188 * _tmp327 - _tmp23 * _tmp328 + _tmp326 * _tmp61 - _tmp330 * _tmp61)
    )
    _jacobian[2, 16] = _tmp145 * (
        -_tmp136 * (-_tmp190 * _tmp36 + _tmp192 * _tmp327 + _tmp193 * _tmp327 - _tmp328 * _tmp61)
        + _tmp143 * _tmp329
        - _tmp162 * _tmp329
    )
    _jacobian[3, 16] = _tmp151 * (
        _tmp147 * _tmp329
        - _tmp149 * (_tmp219 * _tmp327 + _tmp22 * _tmp328 + _tmp330 * _tmp63 - _tmp331 * _tmp36)
        - _tmp163 * _tmp329
    )
    _jacobian[0, 17] = -_tmp1 * _tmp195 - _tmp38 * _tmp45
    _jacobian[1, 17] = _tmp138 * (
        _tmp126 * _tmp339
        - _tmp130 * _tmp339
        - _tmp136
        * (
            -_tmp188 * _tmp337
            - _tmp2 * _tmp321
            - _tmp23 * _tmp335
            + _tmp319 * _tmp334
            - _tmp336 * _tmp61
        )
    )
    _jacobian[2, 17] = _tmp145 * (
        -_tmp136
        * (
            -_tmp192 * _tmp337
            + _tmp2 * _tmp322
            + _tmp333 * _tmp98
            - _tmp334 * _tmp96
            - _tmp335 * _tmp61
        )
        + _tmp143 * _tmp339
        - _tmp162 * _tmp339
    )
    _jacobian[3, 17] = _tmp151 * (
        _tmp147 * _tmp339
        - _tmp149
        * (
            _tmp2 * _tmp325
            - _tmp219 * _tmp337
            + _tmp22 * _tmp335
            - _tmp324 * _tmp334
            + _tmp336 * _tmp63
        )
        - _tmp163 * _tmp339
    )
    _jacobian[0, 18] = -_tmp30 * _tmp32
    _jacobian[1, 18] = _tmp138 * (
        _tmp126 * _tmp346
        - _tmp130 * _tmp346
        - _tmp136 * (_tmp188 * _tmp340 - _tmp23 * _tmp344 + _tmp341 * _tmp61 - _tmp343 * _tmp61)
    )
    _jacobian[2, 18] = _tmp145 * (
        -_tmp136 * (-_tmp190 * _tmp32 + _tmp192 * _tmp340 + _tmp342 * _tmp96 - _tmp345 * logR[2, 0])
        + _tmp143 * _tmp346
        - _tmp162 * _tmp346
    )
    _jacobian[3, 18] = _tmp151 * (
        _tmp147 * _tmp346
        - _tmp149 * (_tmp219 * _tmp340 + _tmp22 * _tmp344 - _tmp32 * _tmp331 + _tmp343 * _tmp63)
        - _tmp163 * _tmp346
    )
    _jacobian[0, 19] = -_tmp220 * _tmp4 - _tmp39 * _tmp45
    _jacobian[1, 19] = _tmp138 * (
        _tmp126 * _tmp352
        - _tmp130 * _tmp352
        - _tmp136
        * (
            _tmp182 * _tmp311 * _tmp354
            - _tmp188 * _tmp353
            - _tmp208 * _tmp354
            - _tmp23 * _tmp350
            - _tmp347 * _tmp61
        )
    )
    _jacobian[2, 19] = _tmp145 * (
        -_tmp136
        * (
            -_tmp192 * _tmp353
            + _tmp322 * _tmp5
            - _tmp323 * _tmp348
            + _tmp348 * _tmp99
            - _tmp350 * _tmp61
        )
        + _tmp143 * _tmp352
        - _tmp162 * _tmp352
    )
    _jacobian[3, 19] = _tmp151 * (
        _tmp147 * _tmp352
        - _tmp149
        * (
            -_tmp219 * _tmp353
            + _tmp22 * _tmp350
            - _tmp324 * _tmp349
            + _tmp347 * _tmp63
            + _tmp351 * _tmp63
        )
        - _tmp163 * _tmp352
    )
    _jacobian[0, 20] = -_tmp30 * _tmp34
    _jacobian[1, 20] = _tmp138 * (
        _tmp126 * _tmp358
        - _tmp130 * _tmp358
        - _tmp136 * (_tmp188 * _tmp356 - _tmp218 * _tmp356 - _tmp23 * _tmp357 + _tmp355 * _tmp61)
    )
    _jacobian[2, 20] = _tmp145 * (
        -_tmp136 * (-_tmp190 * _tmp34 + _tmp192 * _tmp356 + _tmp193 * _tmp356 - _tmp357 * _tmp61)
        + _tmp143 * _tmp358
        - _tmp162 * _tmp358
    )
    _jacobian[3, 20] = _tmp151 * (
        _tmp147 * _tmp358
        - _tmp149 * (_tmp194 * _tmp356 + _tmp219 * _tmp356 + _tmp22 * _tmp357 - _tmp331 * _tmp34)
        - _tmp163 * _tmp358
    )
    _jacobian[0, 21] = 0
    _jacobian[1, 21] = -_tmp137 * _tmp138
    _jacobian[2, 21] = -_tmp144 * _tmp145
    _jacobian[3, 21] = 0
    _jacobian[0, 22] = 0
    _jacobian[1, 22] = 0
    _jacobian[2, 22] = 0
    _jacobian[3, 22] = -_tmp150 * _tmp151
    _jacobian[0, 23] = 0
    _jacobian[1, 23] = -_tmp138 * _tmp81
    _jacobian[2, 23] = -_tmp302 * _tmp85
    _jacobian[3, 23] = 0
    _jacobian[0, 24] = 0
    _jacobian[1, 24] = 0
    _jacobian[2, 24] = 0
    _jacobian[3, 24] = -_tmp303 * _tmp92
    return _thrust_torque, _jacobian
