# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument,unused-import

import math
import typing as T

import numpy

import sym


def dynamics(ierr, p, v, logR, w, p_d, thrust, torque, dt):
    # type: (numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, float, numpy.ndarray, float) -> T.Tuple[numpy.ndarray, numpy.ndarray]
    """
    This function was autogenerated from a symbolic function. Do not modify by hand.

    Symbolic function: dynamics_symfn

    Args:
        ierr: Matrix31
        p: Matrix31
        v: Matrix31
        logR: Matrix31
        w: Matrix31
        p_d: Matrix31
        thrust: Scalar
        torque: Matrix31
        dt: Scalar

    Outputs:
        ierr_p_v_logR_w: Matrix15_1
        jacobian: (15x19) jacobian of ierr_p_v_logR_w wrt args ierr (3), p (3), v (3), logR (3), w (3),
                  thrust (1), torque (3)
    """

    # Total ops: 714

    # Input arrays
    if ierr.shape == (3,):
        ierr = ierr.reshape((3, 1))
    elif ierr.shape != (3, 1):
        raise IndexError(
            "ierr is expected to have shape (3, 1) or (3,); instead had shape {}".format(ierr.shape)
        )

    if p.shape == (3,):
        p = p.reshape((3, 1))
    elif p.shape != (3, 1):
        raise IndexError(
            "p is expected to have shape (3, 1) or (3,); instead had shape {}".format(p.shape)
        )

    if v.shape == (3,):
        v = v.reshape((3, 1))
    elif v.shape != (3, 1):
        raise IndexError(
            "v is expected to have shape (3, 1) or (3,); instead had shape {}".format(v.shape)
        )

    if logR.shape == (3,):
        logR = logR.reshape((3, 1))
    elif logR.shape != (3, 1):
        raise IndexError(
            "logR is expected to have shape (3, 1) or (3,); instead had shape {}".format(logR.shape)
        )

    if w.shape == (3,):
        w = w.reshape((3, 1))
    elif w.shape != (3, 1):
        raise IndexError(
            "w is expected to have shape (3, 1) or (3,); instead had shape {}".format(w.shape)
        )

    if p_d.shape == (3,):
        p_d = p_d.reshape((3, 1))
    elif p_d.shape != (3, 1):
        raise IndexError(
            "p_d is expected to have shape (3, 1) or (3,); instead had shape {}".format(p_d.shape)
        )

    if torque.shape == (3,):
        torque = torque.reshape((3, 1))
    elif torque.shape != (3, 1):
        raise IndexError(
            "torque is expected to have shape (3, 1) or (3,); instead had shape {}".format(
                torque.shape
            )
        )

    # Intermediate terms (234)
    _tmp0 = logR[0, 0] ** 2
    _tmp1 = logR[2, 0] ** 2
    _tmp2 = logR[1, 0] ** 2
    _tmp3 = _tmp0 + _tmp1 + _tmp2 + 1.0e-12
    _tmp4 = 1 / _tmp3
    _tmp5 = math.sqrt(_tmp3)
    _tmp6 = (1.0 / 2.0) * _tmp5
    _tmp7 = math.sin(_tmp6)
    _tmp8 = _tmp7**2
    _tmp9 = _tmp4 * _tmp8
    _tmp10 = 2 * _tmp9
    _tmp11 = _tmp10 * logR[2, 0]
    _tmp12 = 1 / _tmp5
    _tmp13 = _tmp12 * _tmp7
    _tmp14 = math.cos(_tmp6)
    _tmp15 = 2 * _tmp14
    _tmp16 = _tmp13 * _tmp15
    _tmp17 = dt * (_tmp11 * logR[0, 0] + _tmp16 * logR[1, 0])
    _tmp18 = _tmp10 * logR[1, 0]
    _tmp19 = dt * (-_tmp16 * logR[0, 0] + _tmp18 * logR[2, 0])
    _tmp20 = _tmp2 * _tmp9
    _tmp21 = _tmp0 * _tmp9
    _tmp22 = -2 * _tmp20 - 2 * _tmp21 + 1
    _tmp23 = w[2, 0] ** 2
    _tmp24 = dt**2
    _tmp25 = w[1, 0] ** 2
    _tmp26 = w[0, 0] ** 2
    _tmp27 = _tmp23 * _tmp24 + _tmp24 * _tmp25 + _tmp24 * _tmp26 + 1.0e-12
    _tmp28 = math.sqrt(_tmp27)
    _tmp29 = 1 / _tmp28
    _tmp30 = (1.0 / 2.0) * _tmp28
    _tmp31 = math.sin(_tmp30)
    _tmp32 = _tmp14 * _tmp31
    _tmp33 = _tmp29 * _tmp32
    _tmp34 = _tmp33 * dt
    _tmp35 = _tmp34 * w[0, 0]
    _tmp36 = _tmp29 * dt
    _tmp37 = _tmp13 * _tmp31
    _tmp38 = _tmp37 * w[2, 0]
    _tmp39 = _tmp36 * _tmp38
    _tmp40 = _tmp39 * logR[1, 0]
    _tmp41 = _tmp36 * _tmp37
    _tmp42 = _tmp41 * logR[2, 0]
    _tmp43 = _tmp42 * w[1, 0]
    _tmp44 = math.cos(_tmp30)
    _tmp45 = _tmp44 * _tmp7
    _tmp46 = _tmp12 * _tmp45
    _tmp47 = _tmp46 * logR[0, 0]
    _tmp48 = _tmp35 + _tmp40 - _tmp43 + _tmp47
    _tmp49 = _tmp14 * _tmp44
    _tmp50 = _tmp39 * logR[2, 0]
    _tmp51 = _tmp41 * logR[1, 0]
    _tmp52 = _tmp51 * w[1, 0]
    _tmp53 = _tmp41 * w[0, 0]
    _tmp54 = _tmp50 + _tmp52 + _tmp53 * logR[0, 0]
    _tmp55 = _tmp49 - _tmp54
    _tmp56 = abs(_tmp55)
    _tmp57 = min(0.999999, _tmp56)
    _tmp58 = 1 - _tmp57**2
    _tmp59 = math.acos(_tmp57)
    _tmp60 = 0.0 if _tmp55 == 0 else math.copysign(1, _tmp55)
    _tmp61 = 2 * min(0, _tmp60) + 1
    _tmp62 = 2 * _tmp61
    _tmp63 = _tmp59 * _tmp62 / math.sqrt(_tmp58)
    _tmp64 = _tmp34 * w[1, 0]
    _tmp65 = _tmp39 * logR[0, 0]
    _tmp66 = _tmp46 * logR[1, 0]
    _tmp67 = _tmp53 * logR[2, 0] + _tmp64 - _tmp65 + _tmp66
    _tmp68 = _tmp46 * logR[2, 0]
    _tmp69 = _tmp34 * w[2, 0]
    _tmp70 = _tmp41 * logR[0, 0]
    _tmp71 = _tmp70 * w[1, 0]
    _tmp72 = -_tmp53 * logR[1, 0] + _tmp68 + _tmp69 + _tmp71
    _tmp73 = _tmp3 ** (-3.0 / 2.0)
    _tmp74 = _tmp7 * _tmp73
    _tmp75 = _tmp15 * _tmp74
    _tmp76 = _tmp0 * _tmp75
    _tmp77 = _tmp76 * logR[2, 0]
    _tmp78 = _tmp14**2 * _tmp4
    _tmp79 = logR[0, 0] * logR[1, 0]
    _tmp80 = _tmp78 * _tmp79
    _tmp81 = _tmp79 * _tmp9
    _tmp82 = 4 * _tmp8 / _tmp3**2
    _tmp83 = _tmp82 * logR[2, 0]
    _tmp84 = _tmp0 * _tmp83
    _tmp85 = _tmp75 * _tmp79
    _tmp86 = dt * thrust
    _tmp87 = -_tmp79 * _tmp83 + _tmp85 * logR[2, 0]
    _tmp88 = _tmp2 * _tmp82
    _tmp89 = logR[0, 0] ** 3
    _tmp90 = 4 * _tmp9
    _tmp91 = _tmp2 * _tmp75
    _tmp92 = _tmp48 * _tmp61
    _tmp93 = (1.0 / 2.0) * _tmp47
    _tmp94 = logR[0, 0] * logR[2, 0]
    _tmp95 = (1.0 / 2.0) * _tmp4
    _tmp96 = _tmp69 * _tmp95
    _tmp97 = _tmp94 * _tmp96
    _tmp98 = _tmp31 * _tmp36 * _tmp74
    _tmp99 = _tmp98 * w[2, 0]
    _tmp100 = _tmp94 * _tmp99
    _tmp101 = _tmp35 * _tmp95
    _tmp102 = _tmp98 * w[0, 0]
    _tmp103 = _tmp98 * w[1, 0]
    _tmp104 = _tmp64 * _tmp95
    _tmp105 = -_tmp103 * _tmp79 + _tmp104 * _tmp79
    _tmp106 = _tmp0 * _tmp101 - _tmp0 * _tmp102 - _tmp100 + _tmp105 + _tmp53 + _tmp93 + _tmp97
    _tmp107 = -_tmp49 + _tmp54
    _tmp108 = abs(_tmp107)
    _tmp109 = min(0.999999, _tmp108)
    _tmp110 = 1 - _tmp109**2
    _tmp111 = ((0.0 if 0.999999 - _tmp108 == 0 else math.copysign(1, 0.999999 - _tmp108)) + 1) * (
        0.0 if _tmp107 == 0 else math.copysign(1, _tmp107)
    )
    _tmp112 = _tmp111 / _tmp110
    _tmp113 = _tmp106 * _tmp112
    _tmp114 = _tmp79 * _tmp99
    _tmp115 = _tmp103 * _tmp94
    _tmp116 = (1.0 / 2.0) * _tmp49
    _tmp117 = _tmp116 * _tmp4
    _tmp118 = _tmp45 * _tmp73
    _tmp119 = _tmp79 * _tmp96
    _tmp120 = _tmp104 * _tmp94
    _tmp121 = (1.0 / 2.0) * w[0, 0]
    _tmp122 = math.acos(_tmp109)
    _tmp123 = _tmp122 * _tmp62 / math.sqrt(_tmp110)
    _tmp124 = _tmp109 * _tmp111 * _tmp122 / _tmp110 ** (3.0 / 2.0)
    _tmp125 = _tmp106 * _tmp124
    _tmp126 = _tmp61 * _tmp67
    _tmp127 = _tmp117 * _tmp79 - _tmp118 * _tmp79
    _tmp128 = _tmp101 * _tmp94 - _tmp102 * _tmp94
    _tmp129 = _tmp41 * w[1, 0]
    _tmp130 = _tmp102 * _tmp79
    _tmp131 = _tmp101 * _tmp79
    _tmp132 = _tmp117 * _tmp94 - _tmp118 * _tmp94
    _tmp133 = _tmp61 * _tmp72
    _tmp134 = _tmp88 * logR[2, 0]
    _tmp135 = _tmp91 * logR[2, 0]
    _tmp136 = _tmp82 * logR[1, 0]
    _tmp137 = logR[1, 0] ** 3
    _tmp138 = (1.0 / 2.0) * _tmp66
    _tmp139 = logR[1, 0] * logR[2, 0]
    _tmp140 = _tmp139 * _tmp96 - _tmp139 * _tmp99
    _tmp141 = -_tmp103 * _tmp2 + _tmp104 * _tmp2 + _tmp129 - _tmp130 + _tmp131 + _tmp138 + _tmp140
    _tmp142 = _tmp112 * _tmp92
    _tmp143 = _tmp124 * _tmp92
    _tmp144 = _tmp104 * _tmp139
    _tmp145 = _tmp103 * _tmp139
    _tmp146 = _tmp124 * _tmp126
    _tmp147 = _tmp102 * _tmp139
    _tmp148 = _tmp101 * _tmp139
    _tmp149 = _tmp112 * _tmp126
    _tmp150 = _tmp117 * _tmp139 - _tmp118 * _tmp139
    _tmp151 = _tmp112 * _tmp133
    _tmp152 = _tmp124 * _tmp133
    _tmp153 = _tmp1 * logR[0, 0]
    _tmp154 = (1.0 / 2.0) * _tmp68
    _tmp155 = _tmp1 * _tmp96 - _tmp1 * _tmp99 + _tmp128 + _tmp144 - _tmp145 + _tmp154 + _tmp39
    _tmp156 = _tmp24 * _tmp33
    _tmp157 = 1 / _tmp27
    _tmp158 = dt**3
    _tmp159 = _tmp158 * _tmp26
    _tmp160 = _tmp157 * _tmp159
    _tmp161 = _tmp158 * w[0, 0]
    _tmp162 = _tmp27 ** (-3.0 / 2.0)
    _tmp163 = _tmp38 * logR[2, 0]
    _tmp164 = _tmp162 * _tmp163
    _tmp165 = _tmp161 * _tmp164
    _tmp166 = _tmp162 * _tmp37
    _tmp167 = _tmp159 * _tmp166
    _tmp168 = _tmp154 * _tmp157
    _tmp169 = _tmp161 * _tmp168
    _tmp170 = _tmp169 * w[2, 0]
    _tmp171 = -_tmp70
    _tmp172 = _tmp138 * _tmp157
    _tmp173 = _tmp161 * _tmp172
    _tmp174 = _tmp161 * _tmp166
    _tmp175 = logR[1, 0] * w[1, 0]
    _tmp176 = -_tmp173 * w[1, 0] + _tmp174 * _tmp175
    _tmp177 = (
        -_tmp121 * _tmp156
        - _tmp160 * _tmp93
        + _tmp165
        + _tmp167 * logR[0, 0]
        - _tmp170
        + _tmp171
        + _tmp176
    )
    _tmp178 = _tmp60 * (
        (0.0 if 0.999999 - _tmp56 == 0 else math.copysign(1, 0.999999 - _tmp56)) + 1
    )
    _tmp179 = _tmp178 / _tmp58
    _tmp180 = _tmp177 * _tmp179
    _tmp181 = _tmp169 * w[1, 0]
    _tmp182 = _tmp24 * _tmp29
    _tmp183 = _tmp182 * _tmp37
    _tmp184 = _tmp121 * _tmp183
    _tmp185 = _tmp173 * w[2, 0]
    _tmp186 = _tmp116 * _tmp157
    _tmp187 = _tmp162 * _tmp32
    _tmp188 = _tmp158 * _tmp187
    _tmp189 = logR[2, 0] * w[1, 0]
    _tmp190 = _tmp174 * _tmp189
    _tmp191 = _tmp162 * _tmp38
    _tmp192 = _tmp161 * _tmp191
    _tmp193 = _tmp192 * logR[1, 0]
    _tmp194 = _tmp178 * _tmp57 * _tmp59 / _tmp58 ** (3.0 / 2.0)
    _tmp195 = _tmp177 * _tmp194
    _tmp196 = _tmp157 * _tmp93
    _tmp197 = _tmp161 * _tmp196
    _tmp198 = _tmp192 * logR[0, 0] - _tmp197 * w[2, 0]
    _tmp199 = _tmp188 * w[0, 0]
    _tmp200 = _tmp158 * _tmp186
    _tmp201 = _tmp200 * w[0, 0]
    _tmp202 = -_tmp199 * w[1, 0] + _tmp201 * w[1, 0]
    _tmp203 = -_tmp51
    _tmp204 = logR[0, 0] * w[1, 0]
    _tmp205 = _tmp174 * _tmp204
    _tmp206 = _tmp197 * w[1, 0]
    _tmp207 = -_tmp199 * w[2, 0] + _tmp201 * w[2, 0]
    _tmp208 = -_tmp42
    _tmp209 = w[1, 0] * w[2, 0]
    _tmp210 = _tmp158 * _tmp209
    _tmp211 = _tmp172 * _tmp210
    _tmp212 = _tmp158 * _tmp191
    _tmp213 = _tmp175 * _tmp212
    _tmp214 = _tmp158 * _tmp25
    _tmp215 = _tmp157 * _tmp214
    _tmp216 = _tmp166 * _tmp214
    _tmp217 = (1.0 / 2.0) * _tmp183
    _tmp218 = (1.0 / 2.0) * _tmp156
    _tmp219 = _tmp158 * _tmp164 * w[1, 0] - _tmp168 * _tmp210
    _tmp220 = (
        -_tmp138 * _tmp215
        + _tmp203
        + _tmp205
        - _tmp206
        + _tmp216 * logR[1, 0]
        - _tmp218 * w[1, 0]
        + _tmp219
    )
    _tmp221 = _tmp179 * _tmp220
    _tmp222 = _tmp194 * _tmp220
    _tmp223 = _tmp204 * _tmp212
    _tmp224 = _tmp196 * _tmp210
    _tmp225 = -_tmp188 * _tmp209 + _tmp200 * _tmp209
    _tmp226 = _tmp158 * _tmp23
    _tmp227 = _tmp157 * _tmp226
    _tmp228 = _tmp166 * _tmp226
    _tmp229 = (1.0 / 2.0) * _tmp182
    _tmp230 = _tmp229 * _tmp38
    _tmp231 = (
        -_tmp154 * _tmp227
        + _tmp198
        + _tmp208
        - _tmp211
        + _tmp213
        - _tmp218 * w[2, 0]
        + _tmp228 * logR[2, 0]
    )
    _tmp232 = _tmp179 * _tmp231
    _tmp233 = _tmp194 * _tmp231

    # Output terms
    _ierr_p_v_logR_w = numpy.zeros(15)
    _ierr_p_v_logR_w[0] = dt * (p[0, 0] - p_d[0, 0]) + ierr[0, 0]
    _ierr_p_v_logR_w[1] = dt * (p[1, 0] - p_d[1, 0]) + ierr[1, 0]
    _ierr_p_v_logR_w[2] = dt * (p[2, 0] - p_d[2, 0]) + ierr[2, 0]
    _ierr_p_v_logR_w[3] = dt * v[0, 0] + p[0, 0]
    _ierr_p_v_logR_w[4] = dt * v[1, 0] + p[1, 0]
    _ierr_p_v_logR_w[5] = dt * v[2, 0] + p[2, 0]
    _ierr_p_v_logR_w[6] = _tmp17 * thrust + v[0, 0]
    _ierr_p_v_logR_w[7] = _tmp19 * thrust + v[1, 0]
    _ierr_p_v_logR_w[8] = dt * (_tmp22 * thrust - 9.81) + v[2, 0]
    _ierr_p_v_logR_w[9] = _tmp48 * _tmp63
    _ierr_p_v_logR_w[10] = _tmp63 * _tmp67
    _ierr_p_v_logR_w[11] = _tmp63 * _tmp72
    _ierr_p_v_logR_w[12] = dt * torque[0, 0] + w[0, 0]
    _ierr_p_v_logR_w[13] = dt * torque[1, 0] + w[1, 0]
    _ierr_p_v_logR_w[14] = dt * torque[2, 0] + w[2, 0]
    _jacobian = numpy.zeros((15, 19))
    _jacobian[0, 0] = 1
    _jacobian[1, 0] = 0
    _jacobian[2, 0] = 0
    _jacobian[3, 0] = 0
    _jacobian[4, 0] = 0
    _jacobian[5, 0] = 0
    _jacobian[6, 0] = 0
    _jacobian[7, 0] = 0
    _jacobian[8, 0] = 0
    _jacobian[9, 0] = 0
    _jacobian[10, 0] = 0
    _jacobian[11, 0] = 0
    _jacobian[12, 0] = 0
    _jacobian[13, 0] = 0
    _jacobian[14, 0] = 0
    _jacobian[0, 1] = 0
    _jacobian[1, 1] = 1
    _jacobian[2, 1] = 0
    _jacobian[3, 1] = 0
    _jacobian[4, 1] = 0
    _jacobian[5, 1] = 0
    _jacobian[6, 1] = 0
    _jacobian[7, 1] = 0
    _jacobian[8, 1] = 0
    _jacobian[9, 1] = 0
    _jacobian[10, 1] = 0
    _jacobian[11, 1] = 0
    _jacobian[12, 1] = 0
    _jacobian[13, 1] = 0
    _jacobian[14, 1] = 0
    _jacobian[0, 2] = 0
    _jacobian[1, 2] = 0
    _jacobian[2, 2] = 1
    _jacobian[3, 2] = 0
    _jacobian[4, 2] = 0
    _jacobian[5, 2] = 0
    _jacobian[6, 2] = 0
    _jacobian[7, 2] = 0
    _jacobian[8, 2] = 0
    _jacobian[9, 2] = 0
    _jacobian[10, 2] = 0
    _jacobian[11, 2] = 0
    _jacobian[12, 2] = 0
    _jacobian[13, 2] = 0
    _jacobian[14, 2] = 0
    _jacobian[0, 3] = dt
    _jacobian[1, 3] = 0
    _jacobian[2, 3] = 0
    _jacobian[3, 3] = 1
    _jacobian[4, 3] = 0
    _jacobian[5, 3] = 0
    _jacobian[6, 3] = 0
    _jacobian[7, 3] = 0
    _jacobian[8, 3] = 0
    _jacobian[9, 3] = 0
    _jacobian[10, 3] = 0
    _jacobian[11, 3] = 0
    _jacobian[12, 3] = 0
    _jacobian[13, 3] = 0
    _jacobian[14, 3] = 0
    _jacobian[0, 4] = 0
    _jacobian[1, 4] = dt
    _jacobian[2, 4] = 0
    _jacobian[3, 4] = 0
    _jacobian[4, 4] = 1
    _jacobian[5, 4] = 0
    _jacobian[6, 4] = 0
    _jacobian[7, 4] = 0
    _jacobian[8, 4] = 0
    _jacobian[9, 4] = 0
    _jacobian[10, 4] = 0
    _jacobian[11, 4] = 0
    _jacobian[12, 4] = 0
    _jacobian[13, 4] = 0
    _jacobian[14, 4] = 0
    _jacobian[0, 5] = 0
    _jacobian[1, 5] = 0
    _jacobian[2, 5] = dt
    _jacobian[3, 5] = 0
    _jacobian[4, 5] = 0
    _jacobian[5, 5] = 1
    _jacobian[6, 5] = 0
    _jacobian[7, 5] = 0
    _jacobian[8, 5] = 0
    _jacobian[9, 5] = 0
    _jacobian[10, 5] = 0
    _jacobian[11, 5] = 0
    _jacobian[12, 5] = 0
    _jacobian[13, 5] = 0
    _jacobian[14, 5] = 0
    _jacobian[0, 6] = 0
    _jacobian[1, 6] = 0
    _jacobian[2, 6] = 0
    _jacobian[3, 6] = dt
    _jacobian[4, 6] = 0
    _jacobian[5, 6] = 0
    _jacobian[6, 6] = 1
    _jacobian[7, 6] = 0
    _jacobian[8, 6] = 0
    _jacobian[9, 6] = 0
    _jacobian[10, 6] = 0
    _jacobian[11, 6] = 0
    _jacobian[12, 6] = 0
    _jacobian[13, 6] = 0
    _jacobian[14, 6] = 0
    _jacobian[0, 7] = 0
    _jacobian[1, 7] = 0
    _jacobian[2, 7] = 0
    _jacobian[3, 7] = 0
    _jacobian[4, 7] = dt
    _jacobian[5, 7] = 0
    _jacobian[6, 7] = 0
    _jacobian[7, 7] = 1
    _jacobian[8, 7] = 0
    _jacobian[9, 7] = 0
    _jacobian[10, 7] = 0
    _jacobian[11, 7] = 0
    _jacobian[12, 7] = 0
    _jacobian[13, 7] = 0
    _jacobian[14, 7] = 0
    _jacobian[0, 8] = 0
    _jacobian[1, 8] = 0
    _jacobian[2, 8] = 0
    _jacobian[3, 8] = 0
    _jacobian[4, 8] = 0
    _jacobian[5, 8] = dt
    _jacobian[6, 8] = 0
    _jacobian[7, 8] = 0
    _jacobian[8, 8] = 1
    _jacobian[9, 8] = 0
    _jacobian[10, 8] = 0
    _jacobian[11, 8] = 0
    _jacobian[12, 8] = 0
    _jacobian[13, 8] = 0
    _jacobian[14, 8] = 0
    _jacobian[0, 9] = 0
    _jacobian[1, 9] = 0
    _jacobian[2, 9] = 0
    _jacobian[3, 9] = 0
    _jacobian[4, 9] = 0
    _jacobian[5, 9] = 0
    _jacobian[6, 9] = _tmp86 * (_tmp11 + _tmp77 + _tmp80 - _tmp81 - _tmp84 - _tmp85)
    _jacobian[7, 9] = _tmp86 * (-_tmp0 * _tmp78 - _tmp16 + _tmp21 + _tmp76 + _tmp87)
    _jacobian[8, 9] = _tmp86 * (
        -_tmp75 * _tmp89
        + _tmp82 * _tmp89
        + _tmp88 * logR[0, 0]
        - _tmp90 * logR[0, 0]
        - _tmp91 * logR[0, 0]
    )
    _jacobian[9, 9] = (
        -_tmp113 * _tmp92
        + _tmp123
        * (
            _tmp0 * _tmp117
            - _tmp0 * _tmp118
            - _tmp114
            + _tmp115
            + _tmp119
            - _tmp120
            - _tmp121 * _tmp70
            + _tmp46
        )
        + _tmp125 * _tmp92
    )
    _jacobian[10, 9] = (
        -_tmp113 * _tmp126
        + _tmp123
        * (-_tmp0 * _tmp96 + _tmp0 * _tmp99 + _tmp127 + _tmp128 - _tmp39 - 1.0 / 2.0 * _tmp71)
        + _tmp125 * _tmp126
    )
    _jacobian[11, 9] = (
        -_tmp113 * _tmp133
        + _tmp123
        * (
            -_tmp0 * _tmp103
            + _tmp0 * _tmp104
            + _tmp129
            + _tmp130
            - _tmp131
            + _tmp132
            - 1.0 / 2.0 * _tmp65
        )
        + _tmp125 * _tmp133
    )
    _jacobian[12, 9] = 0
    _jacobian[13, 9] = 0
    _jacobian[14, 9] = 0
    _jacobian[0, 10] = 0
    _jacobian[1, 10] = 0
    _jacobian[2, 10] = 0
    _jacobian[3, 10] = 0
    _jacobian[4, 10] = 0
    _jacobian[5, 10] = 0
    _jacobian[6, 10] = _tmp86 * (_tmp16 + _tmp2 * _tmp78 - _tmp20 + _tmp87 - _tmp91)
    _jacobian[7, 10] = _tmp86 * (_tmp11 - _tmp134 + _tmp135 - _tmp80 + _tmp81 + _tmp85)
    _jacobian[8, 10] = _tmp86 * (
        _tmp0 * _tmp136
        - _tmp137 * _tmp75
        + _tmp137 * _tmp82
        - _tmp76 * logR[1, 0]
        - _tmp90 * logR[1, 0]
    )
    _jacobian[9, 10] = (
        _tmp123
        * (
            -_tmp121 * _tmp51
            + _tmp127
            - _tmp144
            + _tmp145
            + _tmp2 * _tmp96
            - _tmp2 * _tmp99
            + _tmp39
        )
        - _tmp141 * _tmp142
        + _tmp141 * _tmp143
    )
    _jacobian[10, 10] = (
        _tmp123
        * (
            _tmp114
            + _tmp117 * _tmp2
            - _tmp118 * _tmp2
            - _tmp119
            - _tmp147
            + _tmp148
            + _tmp46
            - 1.0 / 2.0 * _tmp52
        )
        + _tmp141 * _tmp146
        - _tmp141 * _tmp149
    )
    _jacobian[11, 10] = (
        _tmp123
        * (-_tmp101 * _tmp2 + _tmp102 * _tmp2 + _tmp105 + _tmp150 - 1.0 / 2.0 * _tmp40 - _tmp53)
        - _tmp141 * _tmp151
        + _tmp141 * _tmp152
    )
    _jacobian[12, 10] = 0
    _jacobian[13, 10] = 0
    _jacobian[14, 10] = 0
    _jacobian[0, 11] = 0
    _jacobian[1, 11] = 0
    _jacobian[2, 11] = 0
    _jacobian[3, 11] = 0
    _jacobian[4, 11] = 0
    _jacobian[5, 11] = 0
    _jacobian[6, 11] = _tmp86 * (
        _tmp10 * logR[0, 0]
        - _tmp139 * _tmp75
        + _tmp139 * _tmp78
        - _tmp139 * _tmp9
        + _tmp153 * _tmp75
        - _tmp153 * _tmp82
    )
    _jacobian[7, 11] = _tmp86 * (
        -_tmp1 * _tmp136
        + _tmp1 * _tmp75 * logR[1, 0]
        + _tmp18
        + _tmp75 * _tmp94
        - _tmp78 * _tmp94
        + _tmp9 * _tmp94
    )
    _jacobian[8, 11] = _tmp86 * (_tmp134 - _tmp135 - _tmp77 + _tmp84)
    _jacobian[9, 11] = (
        _tmp123
        * (_tmp1 * _tmp103 - _tmp1 * _tmp104 - _tmp121 * _tmp42 - _tmp129 + _tmp132 + _tmp140)
        - _tmp142 * _tmp155
        + _tmp143 * _tmp155
    )
    _jacobian[10, 11] = (
        _tmp123
        * (
            _tmp1 * _tmp101
            - _tmp1 * _tmp102
            + _tmp100
            + _tmp150
            - 1.0 / 2.0 * _tmp43
            + _tmp53
            - _tmp97
        )
        + _tmp146 * _tmp155
        - _tmp149 * _tmp155
    )
    _jacobian[11, 11] = (
        _tmp123
        * (
            _tmp1 * _tmp117
            - _tmp1 * _tmp118
            - _tmp115
            + _tmp120
            + _tmp147
            - _tmp148
            + _tmp46
            - 1.0 / 2.0 * _tmp50
        )
        - _tmp151 * _tmp155
        + _tmp152 * _tmp155
    )
    _jacobian[12, 11] = 0
    _jacobian[13, 11] = 0
    _jacobian[14, 11] = 0
    _jacobian[0, 12] = 0
    _jacobian[1, 12] = 0
    _jacobian[2, 12] = 0
    _jacobian[3, 12] = 0
    _jacobian[4, 12] = 0
    _jacobian[5, 12] = 0
    _jacobian[6, 12] = 0
    _jacobian[7, 12] = 0
    _jacobian[8, 12] = 0
    _jacobian[9, 12] = (
        -_tmp180 * _tmp92
        + _tmp195 * _tmp92
        + _tmp63
        * (
            _tmp159 * _tmp186
            - _tmp181
            - _tmp184 * logR[0, 0]
            + _tmp185
            - _tmp188 * _tmp26
            + _tmp190
            - _tmp193
            + _tmp34
        )
    )
    _jacobian[10, 12] = (
        -_tmp126 * _tmp180
        + _tmp126 * _tmp195
        + _tmp63
        * (
            _tmp154 * _tmp160
            - _tmp167 * logR[2, 0]
            - _tmp184 * logR[1, 0]
            + _tmp198
            + _tmp202
            + _tmp42
        )
    )
    _jacobian[11, 12] = (
        -_tmp133 * _tmp180
        + _tmp133 * _tmp195
        + _tmp63
        * (
            -_tmp138 * _tmp160
            + _tmp167 * logR[1, 0]
            - _tmp184 * logR[2, 0]
            + _tmp203
            - _tmp205
            + _tmp206
            + _tmp207
        )
    )
    _jacobian[12, 12] = 1
    _jacobian[13, 12] = 0
    _jacobian[14, 12] = 0
    _jacobian[0, 13] = 0
    _jacobian[1, 13] = 0
    _jacobian[2, 13] = 0
    _jacobian[3, 13] = 0
    _jacobian[4, 13] = 0
    _jacobian[5, 13] = 0
    _jacobian[6, 13] = 0
    _jacobian[7, 13] = 0
    _jacobian[8, 13] = 0
    _jacobian[9, 13] = (
        -_tmp221 * _tmp92
        + _tmp222 * _tmp92
        + _tmp63
        * (
            -_tmp154 * _tmp215
            + _tmp202
            - _tmp204 * _tmp217
            + _tmp208
            + _tmp211
            - _tmp213
            + _tmp216 * logR[2, 0]
        )
    )
    _jacobian[10, 13] = (
        -_tmp126 * _tmp221
        + _tmp126 * _tmp222
        + _tmp63
        * (
            -_tmp175 * _tmp217
            + _tmp181
            + _tmp186 * _tmp214
            - _tmp187 * _tmp214
            - _tmp190
            + _tmp223
            - _tmp224
            + _tmp34
        )
    )
    _jacobian[11, 13] = (
        -_tmp133 * _tmp221
        + _tmp133 * _tmp222
        + _tmp63
        * (_tmp176 - _tmp189 * _tmp217 + _tmp215 * _tmp93 - _tmp216 * logR[0, 0] + _tmp225 + _tmp70)
    )
    _jacobian[12, 13] = 0
    _jacobian[13, 13] = 1
    _jacobian[14, 13] = 0
    _jacobian[0, 14] = 0
    _jacobian[1, 14] = 0
    _jacobian[2, 14] = 0
    _jacobian[3, 14] = 0
    _jacobian[4, 14] = 0
    _jacobian[5, 14] = 0
    _jacobian[6, 14] = 0
    _jacobian[7, 14] = 0
    _jacobian[8, 14] = 0
    _jacobian[9, 14] = (
        -_tmp232 * _tmp92
        + _tmp233 * _tmp92
        + _tmp63
        * (
            _tmp138 * _tmp227
            + _tmp207
            + _tmp219
            - _tmp228 * logR[1, 0]
            - _tmp230 * logR[0, 0]
            + _tmp51
        )
    )
    _jacobian[10, 14] = (
        -_tmp126 * _tmp232
        + _tmp126 * _tmp233
        + _tmp63
        * (
            -_tmp165
            + _tmp170
            + _tmp171
            + _tmp225
            - _tmp227 * _tmp93
            + _tmp228 * logR[0, 0]
            - _tmp230 * logR[1, 0]
        )
    )
    _jacobian[11, 14] = (
        -_tmp133 * _tmp232
        + _tmp133 * _tmp233
        + _tmp63
        * (
            -_tmp163 * _tmp229
            - _tmp185
            + _tmp186 * _tmp226
            - _tmp188 * _tmp23
            + _tmp193
            - _tmp223
            + _tmp224
            + _tmp34
        )
    )
    _jacobian[12, 14] = 0
    _jacobian[13, 14] = 0
    _jacobian[14, 14] = 1
    _jacobian[0, 15] = 0
    _jacobian[1, 15] = 0
    _jacobian[2, 15] = 0
    _jacobian[3, 15] = 0
    _jacobian[4, 15] = 0
    _jacobian[5, 15] = 0
    _jacobian[6, 15] = _tmp17
    _jacobian[7, 15] = _tmp19
    _jacobian[8, 15] = _tmp22 * dt
    _jacobian[9, 15] = 0
    _jacobian[10, 15] = 0
    _jacobian[11, 15] = 0
    _jacobian[12, 15] = 0
    _jacobian[13, 15] = 0
    _jacobian[14, 15] = 0
    _jacobian[0, 16] = 0
    _jacobian[1, 16] = 0
    _jacobian[2, 16] = 0
    _jacobian[3, 16] = 0
    _jacobian[4, 16] = 0
    _jacobian[5, 16] = 0
    _jacobian[6, 16] = 0
    _jacobian[7, 16] = 0
    _jacobian[8, 16] = 0
    _jacobian[9, 16] = 0
    _jacobian[10, 16] = 0
    _jacobian[11, 16] = 0
    _jacobian[12, 16] = dt
    _jacobian[13, 16] = 0
    _jacobian[14, 16] = 0
    _jacobian[0, 17] = 0
    _jacobian[1, 17] = 0
    _jacobian[2, 17] = 0
    _jacobian[3, 17] = 0
    _jacobian[4, 17] = 0
    _jacobian[5, 17] = 0
    _jacobian[6, 17] = 0
    _jacobian[7, 17] = 0
    _jacobian[8, 17] = 0
    _jacobian[9, 17] = 0
    _jacobian[10, 17] = 0
    _jacobian[11, 17] = 0
    _jacobian[12, 17] = 0
    _jacobian[13, 17] = dt
    _jacobian[14, 17] = 0
    _jacobian[0, 18] = 0
    _jacobian[1, 18] = 0
    _jacobian[2, 18] = 0
    _jacobian[3, 18] = 0
    _jacobian[4, 18] = 0
    _jacobian[5, 18] = 0
    _jacobian[6, 18] = 0
    _jacobian[7, 18] = 0
    _jacobian[8, 18] = 0
    _jacobian[9, 18] = 0
    _jacobian[10, 18] = 0
    _jacobian[11, 18] = 0
    _jacobian[12, 18] = 0
    _jacobian[13, 18] = 0
    _jacobian[14, 18] = dt
    return _ierr_p_v_logR_w, _jacobian
