// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once


#include <Eigen/Dense>



namespace sym {


/**
* This function was autogenerated from a symbolic function. Do not modify by hand.
*
* Symbolic function: dynamics_symfn
*
* Args:
*     ierr: Matrix31
*     p: Matrix31
*     v: Matrix31
*     logR: Matrix31
*     w: Matrix31
*     p_d: Matrix31
*     thrust: Scalar
*     torque: Matrix31
*     dt: Scalar
*
* Outputs:
*     ierr_p_v_logR_w: Matrix15_1
*     jacobian: (15x19) jacobian of ierr_p_v_logR_w wrt args ierr (3), p (3), v (3), logR (3), w
*               (3), thrust (1), torque (3)
*/
template <typename Scalar>
void Dynamics(const Eigen::Matrix<Scalar, 3, 1>& ierr, const Eigen::Matrix<Scalar, 3, 1>& p, const Eigen::Matrix<Scalar, 3, 1>& v, const Eigen::Matrix<Scalar, 3, 1>& logR, const Eigen::Matrix<Scalar, 3, 1>& w, const Eigen::Matrix<Scalar, 3, 1>& p_d, const Scalar thrust, const Eigen::Matrix<Scalar, 3, 1>& torque, const Scalar dt, Eigen::Matrix<Scalar, 15, 1>* const ierr_p_v_logR_w = nullptr, Eigen::Matrix<Scalar, 15, 19>* const jacobian = nullptr) {

    // Total ops: 714

    // Input arrays

    // Intermediate terms (234)
    const Scalar _tmp0 = std::pow(logR(0, 0), Scalar(2));
    const Scalar _tmp1 = std::pow(logR(2, 0), Scalar(2));
    const Scalar _tmp2 = std::pow(logR(1, 0), Scalar(2));
    const Scalar _tmp3 = _tmp0 + _tmp1 + _tmp2 + Scalar(9.9999999999999998e-13);
    const Scalar _tmp4 = Scalar(1.0) / (_tmp3);
    const Scalar _tmp5 = std::sqrt(_tmp3);
    const Scalar _tmp6 = (Scalar(1)/Scalar(2))*_tmp5;
    const Scalar _tmp7 = std::sin(_tmp6);
    const Scalar _tmp8 = std::pow(_tmp7, Scalar(2));
    const Scalar _tmp9 = _tmp4*_tmp8;
    const Scalar _tmp10 = 2*_tmp9;
    const Scalar _tmp11 = _tmp10*logR(2, 0);
    const Scalar _tmp12 = Scalar(1.0) / (_tmp5);
    const Scalar _tmp13 = _tmp12*_tmp7;
    const Scalar _tmp14 = std::cos(_tmp6);
    const Scalar _tmp15 = 2*_tmp14;
    const Scalar _tmp16 = _tmp13*_tmp15;
    const Scalar _tmp17 = dt*(_tmp11*logR(0, 0) + _tmp16*logR(1, 0));
    const Scalar _tmp18 = _tmp10*logR(1, 0);
    const Scalar _tmp19 = dt*(-_tmp16*logR(0, 0) + _tmp18*logR(2, 0));
    const Scalar _tmp20 = _tmp2*_tmp9;
    const Scalar _tmp21 = _tmp0*_tmp9;
    const Scalar _tmp22 = -2*_tmp20 - 2*_tmp21 + 1;
    const Scalar _tmp23 = std::pow(w(2, 0), Scalar(2));
    const Scalar _tmp24 = std::pow(dt, Scalar(2));
    const Scalar _tmp25 = std::pow(w(1, 0), Scalar(2));
    const Scalar _tmp26 = std::pow(w(0, 0), Scalar(2));
    const Scalar _tmp27 = _tmp23*_tmp24 + _tmp24*_tmp25 + _tmp24*_tmp26 + Scalar(9.9999999999999998e-13);
    const Scalar _tmp28 = std::sqrt(_tmp27);
    const Scalar _tmp29 = Scalar(1.0) / (_tmp28);
    const Scalar _tmp30 = (Scalar(1)/Scalar(2))*_tmp28;
    const Scalar _tmp31 = std::sin(_tmp30);
    const Scalar _tmp32 = _tmp14*_tmp31;
    const Scalar _tmp33 = _tmp29*_tmp32;
    const Scalar _tmp34 = _tmp33*dt;
    const Scalar _tmp35 = _tmp34*w(0, 0);
    const Scalar _tmp36 = _tmp29*dt;
    const Scalar _tmp37 = _tmp13*_tmp31;
    const Scalar _tmp38 = _tmp37*w(2, 0);
    const Scalar _tmp39 = _tmp36*_tmp38;
    const Scalar _tmp40 = _tmp39*logR(1, 0);
    const Scalar _tmp41 = _tmp36*_tmp37;
    const Scalar _tmp42 = _tmp41*logR(2, 0);
    const Scalar _tmp43 = _tmp42*w(1, 0);
    const Scalar _tmp44 = std::cos(_tmp30);
    const Scalar _tmp45 = _tmp44*_tmp7;
    const Scalar _tmp46 = _tmp12*_tmp45;
    const Scalar _tmp47 = _tmp46*logR(0, 0);
    const Scalar _tmp48 = _tmp35 + _tmp40 - _tmp43 + _tmp47;
    const Scalar _tmp49 = _tmp14*_tmp44;
    const Scalar _tmp50 = _tmp39*logR(2, 0);
    const Scalar _tmp51 = _tmp41*logR(1, 0);
    const Scalar _tmp52 = _tmp51*w(1, 0);
    const Scalar _tmp53 = _tmp41*w(0, 0);
    const Scalar _tmp54 = _tmp50 + _tmp52 + _tmp53*logR(0, 0);
    const Scalar _tmp55 = _tmp49 - _tmp54;
    const Scalar _tmp56 = std::fabs(_tmp55);
    const Scalar _tmp57 = std::min<Scalar>(Scalar(0.99999899999999997), _tmp56);
    const Scalar _tmp58 = 1 - std::pow(_tmp57, Scalar(2));
    const Scalar _tmp59 = std::acos(_tmp57);
    const Scalar _tmp60 = (((_tmp55) > 0) - ((_tmp55) < 0));
    const Scalar _tmp61 = 2*std::min<Scalar>(0, _tmp60) + 1;
    const Scalar _tmp62 = 2*_tmp61;
    const Scalar _tmp63 = _tmp59*_tmp62/std::sqrt(_tmp58);
    const Scalar _tmp64 = _tmp34*w(1, 0);
    const Scalar _tmp65 = _tmp39*logR(0, 0);
    const Scalar _tmp66 = _tmp46*logR(1, 0);
    const Scalar _tmp67 = _tmp53*logR(2, 0) + _tmp64 - _tmp65 + _tmp66;
    const Scalar _tmp68 = _tmp46*logR(2, 0);
    const Scalar _tmp69 = _tmp34*w(2, 0);
    const Scalar _tmp70 = _tmp41*logR(0, 0);
    const Scalar _tmp71 = _tmp70*w(1, 0);
    const Scalar _tmp72 = -_tmp53*logR(1, 0) + _tmp68 + _tmp69 + _tmp71;
    const Scalar _tmp73 = std::pow(_tmp3, Scalar(Scalar(-3)/Scalar(2)));
    const Scalar _tmp74 = _tmp7*_tmp73;
    const Scalar _tmp75 = _tmp15*_tmp74;
    const Scalar _tmp76 = _tmp0*_tmp75;
    const Scalar _tmp77 = _tmp76*logR(2, 0);
    const Scalar _tmp78 = std::pow(_tmp14, Scalar(2))*_tmp4;
    const Scalar _tmp79 = logR(0, 0)*logR(1, 0);
    const Scalar _tmp80 = _tmp78*_tmp79;
    const Scalar _tmp81 = _tmp79*_tmp9;
    const Scalar _tmp82 = 4*_tmp8/std::pow(_tmp3, Scalar(2));
    const Scalar _tmp83 = _tmp82*logR(2, 0);
    const Scalar _tmp84 = _tmp0*_tmp83;
    const Scalar _tmp85 = _tmp75*_tmp79;
    const Scalar _tmp86 = dt*thrust;
    const Scalar _tmp87 = -_tmp79*_tmp83 + _tmp85*logR(2, 0);
    const Scalar _tmp88 = _tmp2*_tmp82;
    const Scalar _tmp89 = [&]() { const Scalar base = logR(0, 0); return base * base * base; }();
    const Scalar _tmp90 = 4*_tmp9;
    const Scalar _tmp91 = _tmp2*_tmp75;
    const Scalar _tmp92 = _tmp48*_tmp61;
    const Scalar _tmp93 = (Scalar(1)/Scalar(2))*_tmp47;
    const Scalar _tmp94 = logR(0, 0)*logR(2, 0);
    const Scalar _tmp95 = (Scalar(1)/Scalar(2))*_tmp4;
    const Scalar _tmp96 = _tmp69*_tmp95;
    const Scalar _tmp97 = _tmp94*_tmp96;
    const Scalar _tmp98 = _tmp31*_tmp36*_tmp74;
    const Scalar _tmp99 = _tmp98*w(2, 0);
    const Scalar _tmp100 = _tmp94*_tmp99;
    const Scalar _tmp101 = _tmp35*_tmp95;
    const Scalar _tmp102 = _tmp98*w(0, 0);
    const Scalar _tmp103 = _tmp98*w(1, 0);
    const Scalar _tmp104 = _tmp64*_tmp95;
    const Scalar _tmp105 = -_tmp103*_tmp79 + _tmp104*_tmp79;
    const Scalar _tmp106 = _tmp0*_tmp101 - _tmp0*_tmp102 - _tmp100 + _tmp105 + _tmp53 + _tmp93 + _tmp97;
    const Scalar _tmp107 = -_tmp49 + _tmp54;
    const Scalar _tmp108 = std::fabs(_tmp107);
    const Scalar _tmp109 = std::min<Scalar>(Scalar(0.99999899999999997), _tmp108);
    const Scalar _tmp110 = 1 - std::pow(_tmp109, Scalar(2));
    const Scalar _tmp111 = ((((Scalar(0.99999899999999997) - _tmp108) > 0) - ((Scalar(0.99999899999999997) - _tmp108) < 0)) + 1)*(((_tmp107) > 0) - ((_tmp107) < 0));
    const Scalar _tmp112 = _tmp111/_tmp110;
    const Scalar _tmp113 = _tmp106*_tmp112;
    const Scalar _tmp114 = _tmp79*_tmp99;
    const Scalar _tmp115 = _tmp103*_tmp94;
    const Scalar _tmp116 = (Scalar(1)/Scalar(2))*_tmp49;
    const Scalar _tmp117 = _tmp116*_tmp4;
    const Scalar _tmp118 = _tmp45*_tmp73;
    const Scalar _tmp119 = _tmp79*_tmp96;
    const Scalar _tmp120 = _tmp104*_tmp94;
    const Scalar _tmp121 = (Scalar(1)/Scalar(2))*w(0, 0);
    const Scalar _tmp122 = std::acos(_tmp109);
    const Scalar _tmp123 = _tmp122*_tmp62/std::sqrt(_tmp110);
    const Scalar _tmp124 = _tmp109*_tmp111*_tmp122/(_tmp110 * std::sqrt(_tmp110));
    const Scalar _tmp125 = _tmp106*_tmp124;
    const Scalar _tmp126 = _tmp61*_tmp67;
    const Scalar _tmp127 = _tmp117*_tmp79 - _tmp118*_tmp79;
    const Scalar _tmp128 = _tmp101*_tmp94 - _tmp102*_tmp94;
    const Scalar _tmp129 = _tmp41*w(1, 0);
    const Scalar _tmp130 = _tmp102*_tmp79;
    const Scalar _tmp131 = _tmp101*_tmp79;
    const Scalar _tmp132 = _tmp117*_tmp94 - _tmp118*_tmp94;
    const Scalar _tmp133 = _tmp61*_tmp72;
    const Scalar _tmp134 = _tmp88*logR(2, 0);
    const Scalar _tmp135 = _tmp91*logR(2, 0);
    const Scalar _tmp136 = _tmp82*logR(1, 0);
    const Scalar _tmp137 = [&]() { const Scalar base = logR(1, 0); return base * base * base; }();
    const Scalar _tmp138 = (Scalar(1)/Scalar(2))*_tmp66;
    const Scalar _tmp139 = logR(1, 0)*logR(2, 0);
    const Scalar _tmp140 = _tmp139*_tmp96 - _tmp139*_tmp99;
    const Scalar _tmp141 = -_tmp103*_tmp2 + _tmp104*_tmp2 + _tmp129 - _tmp130 + _tmp131 + _tmp138 + _tmp140;
    const Scalar _tmp142 = _tmp112*_tmp92;
    const Scalar _tmp143 = _tmp124*_tmp92;
    const Scalar _tmp144 = _tmp104*_tmp139;
    const Scalar _tmp145 = _tmp103*_tmp139;
    const Scalar _tmp146 = _tmp124*_tmp126;
    const Scalar _tmp147 = _tmp102*_tmp139;
    const Scalar _tmp148 = _tmp101*_tmp139;
    const Scalar _tmp149 = _tmp112*_tmp126;
    const Scalar _tmp150 = _tmp117*_tmp139 - _tmp118*_tmp139;
    const Scalar _tmp151 = _tmp112*_tmp133;
    const Scalar _tmp152 = _tmp124*_tmp133;
    const Scalar _tmp153 = _tmp1*logR(0, 0);
    const Scalar _tmp154 = (Scalar(1)/Scalar(2))*_tmp68;
    const Scalar _tmp155 = _tmp1*_tmp96 - _tmp1*_tmp99 + _tmp128 + _tmp144 - _tmp145 + _tmp154 + _tmp39;
    const Scalar _tmp156 = _tmp24*_tmp33;
    const Scalar _tmp157 = Scalar(1.0) / (_tmp27);
    const Scalar _tmp158 = [&]() { const Scalar base = dt; return base * base * base; }();
    const Scalar _tmp159 = _tmp158*_tmp26;
    const Scalar _tmp160 = _tmp157*_tmp159;
    const Scalar _tmp161 = _tmp158*w(0, 0);
    const Scalar _tmp162 = std::pow(_tmp27, Scalar(Scalar(-3)/Scalar(2)));
    const Scalar _tmp163 = _tmp38*logR(2, 0);
    const Scalar _tmp164 = _tmp162*_tmp163;
    const Scalar _tmp165 = _tmp161*_tmp164;
    const Scalar _tmp166 = _tmp162*_tmp37;
    const Scalar _tmp167 = _tmp159*_tmp166;
    const Scalar _tmp168 = _tmp154*_tmp157;
    const Scalar _tmp169 = _tmp161*_tmp168;
    const Scalar _tmp170 = _tmp169*w(2, 0);
    const Scalar _tmp171 = -_tmp70;
    const Scalar _tmp172 = _tmp138*_tmp157;
    const Scalar _tmp173 = _tmp161*_tmp172;
    const Scalar _tmp174 = _tmp161*_tmp166;
    const Scalar _tmp175 = logR(1, 0)*w(1, 0);
    const Scalar _tmp176 = -_tmp173*w(1, 0) + _tmp174*_tmp175;
    const Scalar _tmp177 = -_tmp121*_tmp156 - _tmp160*_tmp93 + _tmp165 + _tmp167*logR(0, 0) - _tmp170 + _tmp171 + _tmp176;
    const Scalar _tmp178 = _tmp60*((((Scalar(0.99999899999999997) - _tmp56) > 0) - ((Scalar(0.99999899999999997) - _tmp56) < 0)) + 1);
    const Scalar _tmp179 = _tmp178/_tmp58;
    const Scalar _tmp180 = _tmp177*_tmp179;
    const Scalar _tmp181 = _tmp169*w(1, 0);
    const Scalar _tmp182 = _tmp24*_tmp29;
    const Scalar _tmp183 = _tmp182*_tmp37;
    const Scalar _tmp184 = _tmp121*_tmp183;
    const Scalar _tmp185 = _tmp173*w(2, 0);
    const Scalar _tmp186 = _tmp116*_tmp157;
    const Scalar _tmp187 = _tmp162*_tmp32;
    const Scalar _tmp188 = _tmp158*_tmp187;
    const Scalar _tmp189 = logR(2, 0)*w(1, 0);
    const Scalar _tmp190 = _tmp174*_tmp189;
    const Scalar _tmp191 = _tmp162*_tmp38;
    const Scalar _tmp192 = _tmp161*_tmp191;
    const Scalar _tmp193 = _tmp192*logR(1, 0);
    const Scalar _tmp194 = _tmp178*_tmp57*_tmp59/(_tmp58 * std::sqrt(_tmp58));
    const Scalar _tmp195 = _tmp177*_tmp194;
    const Scalar _tmp196 = _tmp157*_tmp93;
    const Scalar _tmp197 = _tmp161*_tmp196;
    const Scalar _tmp198 = _tmp192*logR(0, 0) - _tmp197*w(2, 0);
    const Scalar _tmp199 = _tmp188*w(0, 0);
    const Scalar _tmp200 = _tmp158*_tmp186;
    const Scalar _tmp201 = _tmp200*w(0, 0);
    const Scalar _tmp202 = -_tmp199*w(1, 0) + _tmp201*w(1, 0);
    const Scalar _tmp203 = -_tmp51;
    const Scalar _tmp204 = logR(0, 0)*w(1, 0);
    const Scalar _tmp205 = _tmp174*_tmp204;
    const Scalar _tmp206 = _tmp197*w(1, 0);
    const Scalar _tmp207 = -_tmp199*w(2, 0) + _tmp201*w(2, 0);
    const Scalar _tmp208 = -_tmp42;
    const Scalar _tmp209 = w(1, 0)*w(2, 0);
    const Scalar _tmp210 = _tmp158*_tmp209;
    const Scalar _tmp211 = _tmp172*_tmp210;
    const Scalar _tmp212 = _tmp158*_tmp191;
    const Scalar _tmp213 = _tmp175*_tmp212;
    const Scalar _tmp214 = _tmp158*_tmp25;
    const Scalar _tmp215 = _tmp157*_tmp214;
    const Scalar _tmp216 = _tmp166*_tmp214;
    const Scalar _tmp217 = (Scalar(1)/Scalar(2))*_tmp183;
    const Scalar _tmp218 = (Scalar(1)/Scalar(2))*_tmp156;
    const Scalar _tmp219 = _tmp158*_tmp164*w(1, 0) - _tmp168*_tmp210;
    const Scalar _tmp220 = -_tmp138*_tmp215 + _tmp203 + _tmp205 - _tmp206 + _tmp216*logR(1, 0) - _tmp218*w(1, 0) + _tmp219;
    const Scalar _tmp221 = _tmp179*_tmp220;
    const Scalar _tmp222 = _tmp194*_tmp220;
    const Scalar _tmp223 = _tmp204*_tmp212;
    const Scalar _tmp224 = _tmp196*_tmp210;
    const Scalar _tmp225 = -_tmp188*_tmp209 + _tmp200*_tmp209;
    const Scalar _tmp226 = _tmp158*_tmp23;
    const Scalar _tmp227 = _tmp157*_tmp226;
    const Scalar _tmp228 = _tmp166*_tmp226;
    const Scalar _tmp229 = (Scalar(1)/Scalar(2))*_tmp182;
    const Scalar _tmp230 = _tmp229*_tmp38;
    const Scalar _tmp231 = -_tmp154*_tmp227 + _tmp198 + _tmp208 - _tmp211 + _tmp213 - _tmp218*w(2, 0) + _tmp228*logR(2, 0);
    const Scalar _tmp232 = _tmp179*_tmp231;
    const Scalar _tmp233 = _tmp194*_tmp231;

    // Output terms (2)
    if ( ierr_p_v_logR_w != nullptr ) {
        Eigen::Matrix<Scalar, 15, 1>& _ierr_p_v_logR_w = (*ierr_p_v_logR_w);


        _ierr_p_v_logR_w(0, 0) = dt*(p(0, 0) - p_d(0, 0)) + ierr(0, 0);
        _ierr_p_v_logR_w(1, 0) = dt*(p(1, 0) - p_d(1, 0)) + ierr(1, 0);
        _ierr_p_v_logR_w(2, 0) = dt*(p(2, 0) - p_d(2, 0)) + ierr(2, 0);
        _ierr_p_v_logR_w(3, 0) = dt*v(0, 0) + p(0, 0);
        _ierr_p_v_logR_w(4, 0) = dt*v(1, 0) + p(1, 0);
        _ierr_p_v_logR_w(5, 0) = dt*v(2, 0) + p(2, 0);
        _ierr_p_v_logR_w(6, 0) = _tmp17*thrust + v(0, 0);
        _ierr_p_v_logR_w(7, 0) = _tmp19*thrust + v(1, 0);
        _ierr_p_v_logR_w(8, 0) = dt*(_tmp22*thrust + Scalar(-9.8100000000000005)) + v(2, 0);
        _ierr_p_v_logR_w(9, 0) = _tmp48*_tmp63;
        _ierr_p_v_logR_w(10, 0) = _tmp63*_tmp67;
        _ierr_p_v_logR_w(11, 0) = _tmp63*_tmp72;
        _ierr_p_v_logR_w(12, 0) = dt*torque(0, 0) + w(0, 0);
        _ierr_p_v_logR_w(13, 0) = dt*torque(1, 0) + w(1, 0);
        _ierr_p_v_logR_w(14, 0) = dt*torque(2, 0) + w(2, 0);
    }

    if ( jacobian != nullptr ) {
        Eigen::Matrix<Scalar, 15, 19>& _jacobian = (*jacobian);

        _jacobian.setZero();

        _jacobian(0, 0) = 1;
        _jacobian(1, 1) = 1;
        _jacobian(2, 2) = 1;
        _jacobian(0, 3) = dt;
        _jacobian(3, 3) = 1;
        _jacobian(1, 4) = dt;
        _jacobian(4, 4) = 1;
        _jacobian(2, 5) = dt;
        _jacobian(5, 5) = 1;
        _jacobian(3, 6) = dt;
        _jacobian(6, 6) = 1;
        _jacobian(4, 7) = dt;
        _jacobian(7, 7) = 1;
        _jacobian(5, 8) = dt;
        _jacobian(8, 8) = 1;
        _jacobian(6, 9) = _tmp86*(_tmp11 + _tmp77 + _tmp80 - _tmp81 - _tmp84 - _tmp85);
        _jacobian(7, 9) = _tmp86*(-_tmp0*_tmp78 - _tmp16 + _tmp21 + _tmp76 + _tmp87);
        _jacobian(8, 9) = _tmp86*(-_tmp75*_tmp89 + _tmp82*_tmp89 + _tmp88*logR(0, 0) - _tmp90*logR(0, 0) - _tmp91*logR(0, 0));
        _jacobian(9, 9) = -_tmp113*_tmp92 + _tmp123*(_tmp0*_tmp117 - _tmp0*_tmp118 - _tmp114 + _tmp115 + _tmp119 - _tmp120 - _tmp121*_tmp70 + _tmp46) + _tmp125*_tmp92;
        _jacobian(10, 9) = -_tmp113*_tmp126 + _tmp123*(-_tmp0*_tmp96 + _tmp0*_tmp99 + _tmp127 + _tmp128 - _tmp39 - Scalar(1)/Scalar(2)*_tmp71) + _tmp125*_tmp126;
        _jacobian(11, 9) = -_tmp113*_tmp133 + _tmp123*(-_tmp0*_tmp103 + _tmp0*_tmp104 + _tmp129 + _tmp130 - _tmp131 + _tmp132 - Scalar(1)/Scalar(2)*_tmp65) + _tmp125*_tmp133;
        _jacobian(6, 10) = _tmp86*(_tmp16 + _tmp2*_tmp78 - _tmp20 + _tmp87 - _tmp91);
        _jacobian(7, 10) = _tmp86*(_tmp11 - _tmp134 + _tmp135 - _tmp80 + _tmp81 + _tmp85);
        _jacobian(8, 10) = _tmp86*(_tmp0*_tmp136 - _tmp137*_tmp75 + _tmp137*_tmp82 - _tmp76*logR(1, 0) - _tmp90*logR(1, 0));
        _jacobian(9, 10) = _tmp123*(-_tmp121*_tmp51 + _tmp127 - _tmp144 + _tmp145 + _tmp2*_tmp96 - _tmp2*_tmp99 + _tmp39) - _tmp141*_tmp142 + _tmp141*_tmp143;
        _jacobian(10, 10) = _tmp123*(_tmp114 + _tmp117*_tmp2 - _tmp118*_tmp2 - _tmp119 - _tmp147 + _tmp148 + _tmp46 - Scalar(1)/Scalar(2)*_tmp52) + _tmp141*_tmp146 - _tmp141*_tmp149;
        _jacobian(11, 10) = _tmp123*(-_tmp101*_tmp2 + _tmp102*_tmp2 + _tmp105 + _tmp150 - Scalar(1)/Scalar(2)*_tmp40 - _tmp53) - _tmp141*_tmp151 + _tmp141*_tmp152;
        _jacobian(6, 11) = _tmp86*(_tmp10*logR(0, 0) - _tmp139*_tmp75 + _tmp139*_tmp78 - _tmp139*_tmp9 + _tmp153*_tmp75 - _tmp153*_tmp82);
        _jacobian(7, 11) = _tmp86*(-_tmp1*_tmp136 + _tmp1*_tmp75*logR(1, 0) + _tmp18 + _tmp75*_tmp94 - _tmp78*_tmp94 + _tmp9*_tmp94);
        _jacobian(8, 11) = _tmp86*(_tmp134 - _tmp135 - _tmp77 + _tmp84);
        _jacobian(9, 11) = _tmp123*(_tmp1*_tmp103 - _tmp1*_tmp104 - _tmp121*_tmp42 - _tmp129 + _tmp132 + _tmp140) - _tmp142*_tmp155 + _tmp143*_tmp155;
        _jacobian(10, 11) = _tmp123*(_tmp1*_tmp101 - _tmp1*_tmp102 + _tmp100 + _tmp150 - Scalar(1)/Scalar(2)*_tmp43 + _tmp53 - _tmp97) + _tmp146*_tmp155 - _tmp149*_tmp155;
        _jacobian(11, 11) = _tmp123*(_tmp1*_tmp117 - _tmp1*_tmp118 - _tmp115 + _tmp120 + _tmp147 - _tmp148 + _tmp46 - Scalar(1)/Scalar(2)*_tmp50) - _tmp151*_tmp155 + _tmp152*_tmp155;
        _jacobian(9, 12) = -_tmp180*_tmp92 + _tmp195*_tmp92 + _tmp63*(_tmp159*_tmp186 - _tmp181 - _tmp184*logR(0, 0) + _tmp185 - _tmp188*_tmp26 + _tmp190 - _tmp193 + _tmp34);
        _jacobian(10, 12) = -_tmp126*_tmp180 + _tmp126*_tmp195 + _tmp63*(_tmp154*_tmp160 - _tmp167*logR(2, 0) - _tmp184*logR(1, 0) + _tmp198 + _tmp202 + _tmp42);
        _jacobian(11, 12) = -_tmp133*_tmp180 + _tmp133*_tmp195 + _tmp63*(-_tmp138*_tmp160 + _tmp167*logR(1, 0) - _tmp184*logR(2, 0) + _tmp203 - _tmp205 + _tmp206 + _tmp207);
        _jacobian(12, 12) = 1;
        _jacobian(9, 13) = -_tmp221*_tmp92 + _tmp222*_tmp92 + _tmp63*(-_tmp154*_tmp215 + _tmp202 - _tmp204*_tmp217 + _tmp208 + _tmp211 - _tmp213 + _tmp216*logR(2, 0));
        _jacobian(10, 13) = -_tmp126*_tmp221 + _tmp126*_tmp222 + _tmp63*(-_tmp175*_tmp217 + _tmp181 + _tmp186*_tmp214 - _tmp187*_tmp214 - _tmp190 + _tmp223 - _tmp224 + _tmp34);
        _jacobian(11, 13) = -_tmp133*_tmp221 + _tmp133*_tmp222 + _tmp63*(_tmp176 - _tmp189*_tmp217 + _tmp215*_tmp93 - _tmp216*logR(0, 0) + _tmp225 + _tmp70);
        _jacobian(13, 13) = 1;
        _jacobian(9, 14) = -_tmp232*_tmp92 + _tmp233*_tmp92 + _tmp63*(_tmp138*_tmp227 + _tmp207 + _tmp219 - _tmp228*logR(1, 0) - _tmp230*logR(0, 0) + _tmp51);
        _jacobian(10, 14) = -_tmp126*_tmp232 + _tmp126*_tmp233 + _tmp63*(-_tmp165 + _tmp170 + _tmp171 + _tmp225 - _tmp227*_tmp93 + _tmp228*logR(0, 0) - _tmp230*logR(1, 0));
        _jacobian(11, 14) = -_tmp133*_tmp232 + _tmp133*_tmp233 + _tmp63*(-_tmp163*_tmp229 - _tmp185 + _tmp186*_tmp226 - _tmp188*_tmp23 + _tmp193 - _tmp223 + _tmp224 + _tmp34);
        _jacobian(14, 14) = 1;
        _jacobian(6, 15) = _tmp17;
        _jacobian(7, 15) = _tmp19;
        _jacobian(8, 15) = _tmp22*dt;
        _jacobian(12, 16) = dt;
        _jacobian(13, 17) = dt;
        _jacobian(14, 18) = dt;
    }
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
