name: Python Bindings CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-latest]
        python-version: ["2.7", "3.7"]

    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python Packages
      shell: bash -l {0}
      run: |
        python -m pip install numpy pyyaml pytest scipy

    - name: Build
      shell: bash -l {0}
      run: |
        cd bindings
        CF_PYTHON=python make

    - name: Test
      shell: bash -l {0}
      run: |
        PYTHONPATH=bindings python -m pytest test/bindings
