name: Python Bindings CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-latest]
        python:
          - python-version: "3.7"
            python-cmd: python3
          - python-version: "2.7"
            python-cmd: python2

    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python.python-version }}

    - name: Install Python Packages
      shell: bash -l {0}
      run: |
        ${{ matrix.python.python-cmd }} -m pip install numpy pyyaml pytest scipy

    - name: Build
      shell: bash -l {0}
      run: |
        cd bindings
        CF_PYTHON=${{ matrix.python.python-cmd }} make

    - name: Test
      shell: bash -l {0}
      run: |
        PYTHONPATH=bindings ${{ matrix.python.python-cmd }} -m pytest test/bindings
